import { BeardStyle } from '../domain/grooming';

export const BEARD_STYLES: BeardStyle[] = [
  // 1
  {
    id: 'beard_clean_shaven',
    name: 'Clean Shaven',
    slug: 'clean-shaven',
    description:
      'Completely bare skin spotlighting natural jawline contour, lip line, and facial symmetry.',
    targetLength: 'clean-shaven',
    minimumDensity: 'none',
    shapeCharacteristics: 'clean',
    compatibleFaceShapes: ['oval', 'square', 'diamond', 'rectangle', 'heart', 'triangle', 'round'],
    maintenance: 'high',
    compatibleStyleSlugs: ['minimal', 'formal', 'korean-minimal', 'old-money', 'smart-casual'],
    formalityRange: [1, 5],
    visualTags: ['bare', 'clean', 'sculpted-bone-structure'],
    groomingTips: [
      'Exfoliate prior to wet shave using sharp double-edge safety razor',
      'Finish with alcohol-free soothing aftershave balm',
    ],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 2
  {
    id: 'beard_designer_stubble',
    name: 'Designer Stubble (3-Day Shadow)',
    slug: 'designer-stubble',
    description:
      'Even 1-3mm stubble providing subtle shadow and jawline definition without adding bulk.',
    targetLength: 'stubble',
    minimumDensity: 'patchy',
    shapeCharacteristics: 'natural',
    compatibleFaceShapes: ['oval', 'square', 'round', 'heart', 'diamond', 'rectangle'],
    maintenance: 'minimal',
    compatibleStyleSlugs: ['smart-casual', 'minimal', 'streetwear', 'old-money', 'casual'],
    formalityRange: [1, 4],
    visualTags: ['shadow', 'rugged', 'effortless'],
    groomingTips: [
      'Trim twice weekly with a 1.5mm to 2mm guard',
      'Fade neckline just above Adam’s apple to maintain intentionality',
    ],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 3
  {
    id: 'beard_heavy_stubble',
    name: 'Heavy Stubble (5-Day Shadow)',
    slug: 'heavy-stubble',
    description:
      '4-5mm dense stubble offering strong jaw darkening and masculine texture while remaining clean and modern.',
    targetLength: 'stubble',
    minimumDensity: 'medium',
    shapeCharacteristics: 'sculpted',
    compatibleFaceShapes: ['oval', 'round', 'heart', 'triangle', 'square'],
    maintenance: 'minimal',
    compatibleStyleSlugs: ['smart-casual', 'workwear', 'vintage', 'streetwear'],
    formalityRange: [1, 4],
    visualTags: ['dense-shadow', 'masculine', 'sculpted'],
    groomingTips: [
      'Edge upper cheekline cleanly with a precision blade',
      'Apply daily hydrating beard oil to prevent scratchy bristle texture',
    ],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 4
  {
    id: 'beard_short_boxed',
    name: 'Short Boxed Beard',
    slug: 'short-boxed-beard',
    description:
      'Neatly trimmed full beard kept around 10-15mm with crisp cheek boundaries and a sculpted squared chin line.',
    targetLength: 'short',
    minimumDensity: 'medium',
    shapeCharacteristics: 'sculpted',
    compatibleFaceShapes: ['round', 'oval', 'heart', 'diamond'],
    maintenance: 'moderate',
    compatibleStyleSlugs: ['smart-casual', 'formal', 'old-money', 'workwear'],
    formalityRange: [2, 5],
    visualTags: ['boxed', 'tailored', 'executive', 'jaw-defining'],
    groomingTips: [
      'Square off lower corners below jawline to add masculine angularity',
      'Comb through daily with boar-bristle brush',
    ],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 5
  {
    id: 'beard_tapered_jawline',
    name: 'Tapered Fade Beard',
    slug: 'tapered-fade-beard',
    description:
      'Blended beard starting at skin level by sideburns and grading into denser bulk along jaw and chin.',
    targetLength: 'short',
    minimumDensity: 'medium',
    shapeCharacteristics: 'sculpted',
    compatibleFaceShapes: ['round', 'square', 'oval'],
    maintenance: 'moderate',
    compatibleStyleSlugs: ['streetwear', 'smart-casual', 'minimal', 'techwear'],
    formalityRange: [1, 4],
    visualTags: ['fade', 'gradient', 'sharp', 'contemporary'],
    groomingTips: [
      'Service sideburn fade simultaneously with haircut',
      'Use beard balm for edge discipline',
    ],
    timelessOrTrend: 'TREND',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 6
  {
    id: 'beard_extended_goatee',
    name: 'Extended Sculpted Goatee',
    slug: 'extended-goatee',
    description:
      'Combined mustache and chin beard extending along the jawline with cleanly shaven cheeks. Draws vertical focus down center.',
    targetLength: 'short',
    minimumDensity: 'patchy',
    shapeCharacteristics: 'chin-focused',
    compatibleFaceShapes: ['round', 'square', 'diamond'],
    maintenance: 'moderate',
    compatibleStyleSlugs: ['vintage', 'streetwear', 'casual'],
    formalityRange: [1, 3],
    visualTags: ['goatee', 'angular', 'cheek-shaven'],
    groomingTips: [
      'Keep cheek areas razor-smooth to maintain contrast',
      'Trim mustache corners just slightly below lip line',
    ],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 7
  {
    id: 'beard_full_rugged',
    name: 'Full Rugged Beard',
    slug: 'full-rugged-beard',
    description:
      'Dense natural full growth (25-40mm) kept shaped and conditioned without overly rigid razor lines.',
    targetLength: 'medium',
    minimumDensity: 'thick',
    shapeCharacteristics: 'natural',
    compatibleFaceShapes: ['oval', 'rectangle', 'diamond', 'triangle'],
    maintenance: 'high',
    compatibleStyleSlugs: ['workwear', 'vintage', 'dark-academia'],
    formalityRange: [1, 3],
    visualTags: ['heritage', 'full', 'rugged', 'dense'],
    groomingTips: [
      'Condition with warm beard wash and rich jojoba/argan oils daily',
      'Blow-dry downwards on low heat while brushing to tame stray hairs',
    ],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 8
  {
    id: 'beard_anchor_balbo',
    name: 'Balbo & Anchor Beard',
    slug: 'balbo-anchor',
    description:
      'Soul patch and chin beard shaped like an anchor, accompanied by an unattached trimmed mustache and bare cheeks.',
    targetLength: 'short',
    minimumDensity: 'medium',
    shapeCharacteristics: 'linear',
    compatibleFaceShapes: ['round', 'square'],
    maintenance: 'high',
    compatibleStyleSlugs: ['vintage', 'experimental', 'smart-casual'],
    formalityRange: [2, 4],
    visualTags: ['sculptural', 'artistic', 'distinguished'],
    groomingTips: [
      'Separate mustache from chin beard by at least 2mm clean margin',
      'Requires steady hand with single-blade detailing trimmer',
    ],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 9
  {
    id: 'beard_ducktail_full',
    name: 'Ducktail Shaped Beard',
    slug: 'ducktail-beard',
    description:
      'Full beard with closely tapered cheek hair tapering down to a distinct point at center of chin.',
    targetLength: 'medium',
    minimumDensity: 'thick',
    shapeCharacteristics: 'chin-focused',
    compatibleFaceShapes: ['round', 'oval', 'square'],
    maintenance: 'high',
    compatibleStyleSlugs: ['old-money', 'dark-academia', 'formal'],
    formalityRange: [2, 4],
    visualTags: ['pointed', 'tailored-length', 'elongating'],
    groomingTips: [
      'Direct growth toward center chin point using round brush and wax',
      'Creates vertical emphasis along lower facial line',
    ],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 10
  {
    id: 'beard_refined_chevron_stache',
    name: 'Refined Chevron Mustache with Stubble',
    slug: 'chevron-mustache-stubble',
    description:
      'Prominent full chevron mustache over upper lip supported by subtle 1mm stubble along jaw.',
    targetLength: 'stubble',
    minimumDensity: 'medium',
    shapeCharacteristics: 'natural',
    compatibleFaceShapes: ['square', 'oval', 'rectangle'],
    maintenance: 'moderate',
    compatibleStyleSlugs: ['vintage', 'casual', 'smart-casual', 'korean-minimal'],
    formalityRange: [1, 4],
    visualTags: ['mustache', 'retro', 'statement-grooming', 'editorial'],
    groomingTips: [
      'Trim mustache horizontally just above top lip line',
      'Maintain faint jaw shadow to ground the mustache prominence',
    ],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 11
  {
    id: 'beard_corporate_neat',
    name: 'Corporate Low-Cut Beard',
    slug: 'corporate-beard',
    description:
      'Disciplined 6-8mm uniform beard clipped closely with razor-sharp cheekline and pristine neckline 1 inch above Adam’s apple.',
    targetLength: 'short',
    minimumDensity: 'medium',
    shapeCharacteristics: 'sculpted',
    compatibleFaceShapes: ['oval', 'square', 'rectangle', 'round'],
    maintenance: 'moderate',
    compatibleStyleSlugs: ['formal', 'old-money', 'smart-casual'],
    formalityRange: [3, 5],
    visualTags: ['executive', 'disciplined', 'boardroom-ready'],
    groomingTips: [
      'Trim every 3-4 days with an 8mm guard',
      'Comb straight down with sandalwood comb before shaving edges',
    ],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 12
  {
    id: 'beard_classic_goatee',
    name: 'Classic Circular Goatee',
    slug: 'classic-circular-goatee',
    description:
      'Continuous circular ring of mustache joining a compact chin beard, leaving the jawline and cheeks completely bare.',
    targetLength: 'short',
    minimumDensity: 'patchy',
    shapeCharacteristics: 'chin-focused',
    compatibleFaceShapes: ['round', 'square', 'oval'],
    maintenance: 'moderate',
    compatibleStyleSlugs: ['vintage', 'streetwear', 'casual'],
    formalityRange: [1, 4],
    visualTags: ['circle-beard', '90s', 'compact'],
    groomingTips: [
      'Shape circular perimeter when dry using foil shaver',
      'Keep cheek areas polished and bare daily',
    ],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 13
  {
    id: 'beard_pencil_mustache',
    name: 'Sleek Pencil Mustache',
    slug: 'pencil-mustache',
    description:
      'Ultra-thin horizontal line clipped just above vermilion border of upper lip, with fully clean-shaven face. Vintage Golden Age cinema flair.',
    targetLength: 'stubble',
    minimumDensity: 'medium',
    shapeCharacteristics: 'linear',
    compatibleFaceShapes: ['oval', 'rectangle', 'square'],
    maintenance: 'high',
    compatibleStyleSlugs: ['vintage', 'experimental', 'formal'],
    formalityRange: [2, 5],
    visualTags: ['pencil', 'retro-cinema', 'dapper', 'delicate'],
    groomingTips: [
      'Shave gap between nose and mustache with detail razor',
      'Requires daily perimeter maintenance',
    ],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 14
  {
    id: 'beard_handlebar_mustache',
    name: 'Handlebar Mustache with Bare Cheeks',
    slug: 'handlebar-mustache',
    description:
      'Full dense mustache with extended curled upward tips held by botanical wax, paired with clean-shaven or short stubble cheeks.',
    targetLength: 'short',
    minimumDensity: 'thick',
    shapeCharacteristics: 'sculpted',
    compatibleFaceShapes: ['square', 'oval', 'rectangle'],
    maintenance: 'high',
    compatibleStyleSlugs: ['vintage', 'workwear', 'experimental'],
    formalityRange: [2, 4],
    visualTags: ['handlebar', 'heritage-craft', 'statement'],
    groomingTips: [
      'Train tips outward from center parting with stiff mustache wax',
      'Never trim center hairs; comb them sideways into ends',
    ],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 15
  {
    id: 'beard_five_o_clock_shadow_light',
    name: 'Micro Shadow (1-Day Scruff)',
    slug: 'one-day-micro-shadow',
    description:
      'Subtle 0.5mm shadow providing faint tonal contrast across lower face without formal beard presence.',
    targetLength: 'stubble',
    minimumDensity: 'patchy',
    shapeCharacteristics: 'natural',
    compatibleFaceShapes: ['oval', 'square', 'heart', 'round', 'diamond'],
    maintenance: 'minimal',
    compatibleStyleSlugs: ['minimal', 'korean-minimal', 'smart-casual', 'casual'],
    formalityRange: [1, 5],
    visualTags: ['micro-shadow', 'effortless', 'barely-there'],
    groomingTips: [
      'Shave daily with electric foil trimmer without guard',
      'Hydrate with non-greasy matte face moisturizer',
    ],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 16
  {
    id: 'beard_chin_strap_modern',
    name: 'Modern Sculpted Chin Strap',
    slug: 'modern-chin-strap',
    description:
      'Disciplined narrow band of facial hair tracing jawline from sideburns to chin, leaving upper lip and cheeks bare.',
    targetLength: 'short',
    minimumDensity: 'medium',
    shapeCharacteristics: 'linear',
    compatibleFaceShapes: ['round', 'oval'],
    maintenance: 'high',
    compatibleStyleSlugs: ['streetwear', 'techwear'],
    formalityRange: [1, 3],
    visualTags: ['linear', 'jaw-line', 'sculpted'],
    groomingTips: [
      'Keep upper boundary exactly along mandibular angle',
      'Requires bi-weekly razor edge definition',
    ],
    timelessOrTrend: 'TREND',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 17
  {
    id: 'beard_walrus_mustache',
    name: 'Natural Walrus Mustache',
    slug: 'walrus-mustache',
    description:
      'Heavy bushy mustache cascading down over upper lip in vintage counterculture cadence, accompanied by clean jaw.',
    targetLength: 'medium',
    minimumDensity: 'thick',
    shapeCharacteristics: 'natural',
    compatibleFaceShapes: ['oval', 'square', 'rectangle'],
    maintenance: 'moderate',
    compatibleStyleSlugs: ['vintage', 'workwear', 'dark-academia'],
    formalityRange: [1, 3],
    visualTags: ['walrus', '70s', 'heavy-brush', 'counterculture'],
    groomingTips: [
      'Comb straight down with fine-tooth mustache comb daily',
      'Condition ends with drops of jojoba oil to prevent bristle dryness',
    ],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 18
  {
    id: 'beard_tapered_sideburns_bare',
    name: 'Clean Shaven with Gradient Sideburn Taper',
    slug: 'bare-with-sideburn-fade',
    description:
      'Clean bare face transitioning seamlessly into high-precision gradient skin taper at temporal bone.',
    targetLength: 'clean-shaven',
    minimumDensity: 'none',
    shapeCharacteristics: 'clean',
    compatibleFaceShapes: ['oval', 'square', 'diamond', 'heart', 'round'],
    maintenance: 'high',
    compatibleStyleSlugs: ['minimal', 'korean-minimal', 'formal', 'techwear'],
    formalityRange: [1, 5],
    visualTags: ['bare-skin', 'sideburn-taper', 'architectural'],
    groomingTips: [
      'Service sideburn fade simultaneously with haircut',
      'Wet shave cheeks every morning with botanical shaving cream',
    ],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 19
  {
    id: 'beard_horseshoe_mustache',
    name: 'Sculpted Horseshoe Mustache',
    slug: 'horseshoe-mustache',
    description:
      'Full mustache with vertical pipes extending down past corners of mouth to jawline, cheeks and chin clean.',
    targetLength: 'short',
    minimumDensity: 'medium',
    shapeCharacteristics: 'linear',
    compatibleFaceShapes: ['square', 'oval', 'rectangle'],
    maintenance: 'moderate',
    compatibleStyleSlugs: ['workwear', 'vintage', 'experimental'],
    formalityRange: [1, 3],
    visualTags: ['horseshoe', 'rebellious', 'biker-heritage'],
    groomingTips: [
      'Shave chin center with precision single edge',
      'Keep vertical legs parallel to corner mouth vertical',
    ],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 20
  {
    id: 'beard_chin_curtain_natural',
    name: 'Natural Chin Curtain',
    slug: 'natural-chin-curtain',
    description:
      'Beard following jawline and covering entire chin without mustache. Distinct historical and artistic silhouette.',
    targetLength: 'short',
    minimumDensity: 'medium',
    shapeCharacteristics: 'chin-focused',
    compatibleFaceShapes: ['oval', 'rectangle', 'heart'],
    maintenance: 'moderate',
    compatibleStyleSlugs: ['vintage', 'experimental', 'workwear'],
    formalityRange: [1, 3],
    visualTags: ['chin-curtain', 'lincoln', 'heritage'],
    groomingTips: [
      'Shave upper lip clean every two days',
      'Keep jawline margin symmetrical on both sides',
    ],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
];
