import { BeardStyle } from '../domain/grooming';

export const BEARD_STYLES: BeardStyle[] = [
  {
    id: 'beard_clean_shaven',
    name: 'Clean Shaven',
    slug: 'clean-shaven',
    description:
      'Completely bare skin spotlighting natural jawline contour, lip line, and facial symmetry.',
    targetLength: 'clean-shaven',
    minimumDensity: 'none',
    shapeCharacteristics: 'clean',
    compatibleFaceShapes: ['oval', 'square', 'diamond', 'rectangle', 'heart', 'triangle', 'round'],
    maintenance: 'high',
    compatibleStyleSlugs: ['minimal', 'formal', 'korean-minimal', 'old-money', 'smart-casual'],
    formalityRange: [1, 5],
    visualTags: ['bare', 'clean', 'sculpted-bone-structure'],
    groomingTips: [
      'Exfoliate prior to wet shave using sharp double-edge safety razor',
      'Finish with alcohol-free soothing aftershave balm',
    ],
  },
  {
    id: 'beard_designer_stubble',
    name: 'Designer Stubble (3-Day Shadow)',
    slug: 'designer-stubble',
    description:
      'Even 1-3mm stubble providing subtle shadow and jawline definition without adding bulk.',
    targetLength: 'stubble',
    minimumDensity: 'patchy',
    shapeCharacteristics: 'natural',
    compatibleFaceShapes: ['oval', 'square', 'round', 'heart', 'diamond', 'rectangle'],
    maintenance: 'minimal',
    compatibleStyleSlugs: ['smart-casual', 'minimal', 'streetwear', 'old-money', 'casual'],
    formalityRange: [1, 4],
    visualTags: ['shadow', 'rugged', 'effortless'],
    groomingTips: [
      'Trim twice weekly with a 1.5mm to 2mm guard',
      'Fade neckline just above Adam’s apple to maintain intentionality',
    ],
  },
  {
    id: 'beard_heavy_stubble',
    name: 'Heavy Stubble (5-Day Shadow)',
    slug: 'heavy-stubble',
    description:
      '4-5mm dense stubble offering strong jaw darkening and masculine texture while remaining clean and modern.',
    targetLength: 'stubble',
    minimumDensity: 'medium',
    shapeCharacteristics: 'sculpted',
    compatibleFaceShapes: ['oval', 'round', 'heart', 'triangle'],
    maintenance: 'minimal',
    compatibleStyleSlugs: ['smart-casual', 'workwear', 'vintage', 'streetwear'],
    formalityRange: [1, 4],
    visualTags: ['dense-shadow', 'masculine', 'sculpted'],
    groomingTips: [
      'Edge upper cheekline cleanly with a precision blade',
      'Apply daily hydrating beard oil to prevent scratchy bristle texture',
    ],
  },
  {
    id: 'beard_short_boxed',
    name: 'Short Boxed Beard',
    slug: 'short-boxed-beard',
    description:
      'Neatly trimmed full beard kept around 10-15mm with crisp cheek boundaries and a sculpted squared chin line.',
    targetLength: 'short',
    minimumDensity: 'medium',
    shapeCharacteristics: 'sculpted',
    compatibleFaceShapes: ['round', 'oval', 'heart', 'diamond'],
    maintenance: 'moderate',
    compatibleStyleSlugs: ['smart-casual', 'formal', 'old-money', 'workwear'],
    formalityRange: [2, 5],
    visualTags: ['boxed', 'tailored', 'executive', 'jaw-defining'],
    groomingTips: [
      'Square off lower corners below jawline to add masculine angularity',
      'Comb through daily with boar-bristle brush',
    ],
  },
  {
    id: 'beard_tapered_jawline',
    name: 'Tapered Fade Beard',
    slug: 'tapered-fade-beard',
    description:
      'Blended beard starting at skin level by the sideburns and grading into denser bulk along the jaw and chin.',
    targetLength: 'short',
    minimumDensity: 'medium',
    shapeCharacteristics: 'sculpted',
    compatibleFaceShapes: ['round', 'square', 'oval'],
    maintenance: 'moderate',
    compatibleStyleSlugs: ['streetwear', 'smart-casual', 'minimal', 'techwear'],
    formalityRange: [1, 4],
    visualTags: ['fade', 'gradient', 'sharp', 'contemporary'],
    groomingTips: [
      'Service sideburn fade simultaneously with haircut',
      'Use beard balm for edge discipline',
    ],
  },
  {
    id: 'beard_extended_goatee',
    name: 'Extended Sculpted Goatee',
    slug: 'extended-goatee',
    description:
      'Combined mustache and chin beard extending along the jawline with cleanly shaven cheeks. Draws vertical focus down the center.',
    targetLength: 'short',
    minimumDensity: 'patchy',
    shapeCharacteristics: 'chin-focused',
    compatibleFaceShapes: ['round', 'square', 'diamond'],
    maintenance: 'moderate',
    compatibleStyleSlugs: ['vintage', 'streetwear', 'casual'],
    formalityRange: [1, 3],
    visualTags: ['goatee', 'angular', 'cheek-shaven'],
    groomingTips: [
      'Keep cheek areas razor-smooth to maintain contrast',
      'Trim mustache corners just slightly below lip line',
    ],
  },
  {
    id: 'beard_full_rugged',
    name: 'Full Rugged Beard',
    slug: 'full-rugged-beard',
    description:
      'Dense, natural full growth (25-40mm) kept shaped and conditioned without overly rigid razor lines.',
    targetLength: 'medium',
    minimumDensity: 'thick',
    shapeCharacteristics: 'natural',
    compatibleFaceShapes: ['oval', 'rectangle', 'diamond', 'triangle'],
    maintenance: 'high',
    compatibleStyleSlugs: ['workwear', 'vintage', 'dark-academia'],
    formalityRange: [1, 3],
    visualTags: ['heritage', 'full', 'rugged', 'dense'],
    groomingTips: [
      'Condition with warm beard wash and rich jojoba/argan oils daily',
      'Blow-dry downwards on low heat while brushing to tame stray hairs',
    ],
  },
  {
    id: 'beard_anchor_balbo',
    name: 'Balbo & Anchor Beard',
    slug: 'balbo-anchor',
    description:
      'Soul patch and chin beard shaped like an anchor, accompanied by an unattached trimmed mustache and bare cheeks.',
    targetLength: 'short',
    minimumDensity: 'medium',
    shapeCharacteristics: 'linear',
    compatibleFaceShapes: ['round', 'square'],
    maintenance: 'high',
    compatibleStyleSlugs: ['vintage', 'experimental', 'smart-casual'],
    formalityRange: [2, 4],
    visualTags: ['sculptural', 'artistic', 'distinguished'],
    groomingTips: [
      'Separate mustache from chin beard by at least 2mm clean margin',
      'Requires steady hand with single-blade detailing trimmer',
    ],
  },
  {
    id: 'beard_ducktail_full',
    name: 'Ducktail Shaped Beard',
    slug: 'ducktail-beard',
    description:
      'Full beard with closely tapered cheek hair tapering down to a distinct point at the center of the chin.',
    targetLength: 'medium',
    minimumDensity: 'thick',
    shapeCharacteristics: 'chin-focused',
    compatibleFaceShapes: ['round', 'oval', 'square'],
    maintenance: 'high',
    compatibleStyleSlugs: ['old-money', 'dark-academia', 'formal'],
    formalityRange: [2, 4],
    visualTags: ['pointed', 'tailored-length', 'elongating'],
    groomingTips: [
      'Direct growth toward center chin point using round brush and wax',
      'Elongates rounder faces effectively by creating a lower apex',
    ],
  },
  {
    id: 'beard_refined_chevron_stache',
    name: 'Refined Chevron Mustache with Stubble',
    slug: 'chevron-mustache-stubble',
    description:
      'Prominent full chevron mustache over the upper lip supported by barely-there 1mm stubble along the jaw.',
    targetLength: 'stubble',
    minimumDensity: 'medium',
    shapeCharacteristics: 'natural',
    compatibleFaceShapes: ['square', 'oval', 'rectangle'],
    maintenance: 'moderate',
    compatibleStyleSlugs: ['vintage', 'casual', 'smart-casual', 'korean-minimal'],
    formalityRange: [1, 4],
    visualTags: ['mustache', 'retro', 'statement-grooming', 'editorial'],
    groomingTips: [
      'Trim mustache horizontally just above the top vermilion border',
      'Maintain faint jaw shadow to ground the mustache prominence',
    ],
  },
];
