import { Garment } from '../domain/fashion';

export const GARMENTS: Garment[] = [
  // --- TOPS ---
  {
    id: 'gar_box_tee_white',
    name: 'Heavyweight Boxy Tee (Off-White)',
    slug: 'heavyweight-boxy-tee-offwhite',
    category: 'top',
    subcategory: 't-shirt',
    fit: 'boxy',
    silhouette: 'dropped-shoulder-cropped-hem',
    length: 'regular',
    color: { name: 'off-white', hex: '#FAF9F6', tone: 'neutral', isBaseColor: true },
    material: '300gsm combed organic cotton',
    pattern: 'solid',
    formality: 1,
    seasons: ['spring', 'summer', 'fall', 'all-season'],
    compatibleWeather: ['warm', 'hot', 'mild'],
    compatibleStyleSlugs: ['minimal', 'korean-minimal', 'streetwear', 'casual'],
    layeringRole: 'base',
  },
  {
    id: 'gar_box_tee_black',
    name: 'Heavyweight Boxy Tee (Faded Black)',
    slug: 'heavyweight-boxy-tee-black',
    category: 'top',
    subcategory: 't-shirt',
    fit: 'boxy',
    silhouette: 'dropped-shoulder',
    length: 'regular',
    color: { name: 'faded-black', hex: '#222222', tone: 'neutral', isBaseColor: true },
    material: '320gsm vintage washed cotton',
    pattern: 'solid',
    formality: 1,
    seasons: ['spring', 'summer', 'fall', 'all-season'],
    compatibleWeather: ['warm', 'mild', 'cool'],
    compatibleStyleSlugs: ['streetwear', 'techwear', 'minimal', 'experimental'],
    layeringRole: 'base',
  },
  {
    id: 'gar_knit_polo_olive',
    name: 'Textured Open-Collar Knit Polo',
    slug: 'knit-polo-olive',
    category: 'top',
    subcategory: 'polo',
    fit: 'regular',
    silhouette: 'relaxed-drape',
    length: 'regular',
    color: { name: 'olive', hex: '#556B2F', tone: 'earth', isBaseColor: false },
    material: 'silk-cotton blend knit',
    pattern: 'textured-weave',
    formality: 3,
    seasons: ['spring', 'summer', 'fall'],
    compatibleWeather: ['mild', 'warm'],
    compatibleStyleSlugs: ['smart-casual', 'old-money', 'korean-minimal'],
    layeringRole: 'standalone',
  },
  {
    id: 'gar_oxford_shirt_white',
    name: 'Relaxed Oxford Button-Down Shirt',
    slug: 'relaxed-oxford-white',
    category: 'top',
    subcategory: 'button-down',
    fit: 'relaxed',
    silhouette: 'straight-hang',
    length: 'regular',
    color: { name: 'white', hex: '#FFFFFF', tone: 'neutral', isBaseColor: true },
    material: 'heavyweight oxford cotton',
    pattern: 'solid',
    formality: 3,
    seasons: ['all-season'],
    compatibleWeather: ['mild', 'cool', 'warm'],
    compatibleStyleSlugs: ['smart-casual', 'old-money', 'minimal', 'dark-academia'],
    layeringRole: 'mid',
  },
  {
    id: 'gar_cashmere_crew_charcoal',
    name: 'Fine Merino Cashmere Crewneck',
    slug: 'merino-cashmere-charcoal',
    category: 'top',
    subcategory: 'knitwear',
    fit: 'regular',
    silhouette: 'clean-taper',
    length: 'regular',
    color: { name: 'charcoal', hex: '#36454F', tone: 'neutral', isBaseColor: true },
    material: '90% merino 10% cashmere',
    pattern: 'solid',
    formality: 3,
    seasons: ['fall', 'winter', 'spring'],
    compatibleWeather: ['cool', 'cold'],
    compatibleStyleSlugs: ['minimal', 'smart-casual', 'old-money', 'dark-academia'],
    layeringRole: 'mid',
  },
  {
    id: 'gar_mockneck_black',
    name: 'Minimal Ribbed Mock Neck',
    slug: 'mockneck-black',
    category: 'top',
    subcategory: 'knitwear',
    fit: 'slim',
    silhouette: 'fitted-architectural',
    length: 'regular',
    color: { name: 'jet-black', hex: '#111111', tone: 'neutral', isBaseColor: true },
    material: 'compact modal-wool jersey',
    pattern: 'solid',
    formality: 3,
    seasons: ['fall', 'winter', 'spring'],
    compatibleWeather: ['cool', 'cold'],
    compatibleStyleSlugs: ['minimal', 'techwear', 'smart-casual', 'experimental'],
    layeringRole: 'base',
  },
  {
    id: 'gar_hoodie_heather_grey',
    name: '500GSM Loopback Oversized Hoodie',
    slug: 'heavy-hoodie-grey',
    category: 'top',
    subcategory: 'hoodie',
    fit: 'oversized',
    silhouette: 'box-drape-structured-hood',
    length: 'regular',
    color: { name: 'heather-grey', hex: '#9E9E9E', tone: 'neutral', isBaseColor: true },
    material: '500gsm French terry cotton',
    pattern: 'solid',
    formality: 1,
    seasons: ['fall', 'winter', 'spring'],
    compatibleWeather: ['cool', 'cold', 'windy'],
    compatibleStyleSlugs: ['streetwear', 'casual', 'korean-minimal'],
    layeringRole: 'mid',
  },
  {
    id: 'gar_flannel_overshirt_navy',
    name: 'Brushed Wool Overshirt',
    slug: 'brushed-wool-overshirt-navy',
    category: 'top',
    subcategory: 'overshirt',
    fit: 'relaxed',
    silhouette: 'square-hem-straight',
    length: 'regular',
    color: { name: 'navy', hex: '#000080', tone: 'neutral', isBaseColor: true },
    material: 'boiled wool-cotton blend',
    pattern: 'subtle-stripe',
    formality: 2,
    seasons: ['fall', 'winter', 'spring'],
    compatibleWeather: ['cool', 'cold'],
    compatibleStyleSlugs: ['workwear', 'smart-casual', 'minimal', 'casual'],
    layeringRole: 'outer',
  },
  {
    id: 'gar_crisp_poplin_shirt',
    name: 'Crisp Poplin Point Collar Shirt',
    slug: 'poplin-point-collar-white',
    category: 'top',
    subcategory: 'dress-shirt',
    fit: 'tailored',
    silhouette: 'clean-linear-darted',
    length: 'extended',
    color: { name: 'crisp-white', hex: '#FFFFFF', tone: 'neutral', isBaseColor: true },
    material: '120s two-ply Giza cotton',
    pattern: 'solid',
    formality: 5,
    seasons: ['all-season'],
    compatibleWeather: ['mild', 'warm', 'cool'],
    compatibleStyleSlugs: ['formal', 'old-money', 'smart-casual'],
    layeringRole: 'base',
  },

  // --- OUTERWEAR ---
  {
    id: 'gar_deconstructed_blazer_charcoal',
    name: 'Deconstructed Wool Blazer',
    slug: 'deconstructed-blazer-charcoal',
    category: 'outerwear',
    subcategory: 'blazer',
    fit: 'relaxed',
    silhouette: 'soft-shoulder-fluid-drape',
    length: 'regular',
    color: { name: 'charcoal', hex: '#343838', tone: 'neutral', isBaseColor: true },
    material: 'tropical virgin wool',
    pattern: 'solid',
    formality: 3,
    seasons: ['spring', 'fall', 'all-season'],
    compatibleWeather: ['mild', 'cool'],
    compatibleStyleSlugs: ['korean-minimal', 'smart-casual', 'minimal'],
    layeringRole: 'outer',
  },
  {
    id: 'gar_wool_overcoat_camel',
    name: 'Double-Breasted Wool Overcoat',
    slug: 'double-breasted-overcoat-camel',
    category: 'outerwear',
    subcategory: 'overcoat',
    fit: 'relaxed',
    silhouette: 'architectural-longline',
    length: 'extended',
    color: { name: 'camel', hex: '#C19A6B', tone: 'earth', isBaseColor: false },
    material: 'heavyweight melton wool',
    pattern: 'solid',
    formality: 4,
    seasons: ['winter', 'fall'],
    compatibleWeather: ['cold', 'windy'],
    compatibleStyleSlugs: ['old-money', 'dark-academia', 'smart-casual', 'minimal'],
    layeringRole: 'outer',
  },
  {
    id: 'gar_chore_coat_tan',
    name: 'Duck Canvas Chore Coat',
    slug: 'chore-coat-duck-tan',
    category: 'outerwear',
    subcategory: 'jacket',
    fit: 'regular',
    silhouette: 'boxy-workwear-triple-stitched',
    length: 'regular',
    color: { name: 'canvas-tan', hex: '#D2B48C', tone: 'earth', isBaseColor: false },
    material: '12oz ringspun cotton canvas',
    pattern: 'solid',
    formality: 2,
    seasons: ['spring', 'fall'],
    compatibleWeather: ['mild', 'cool', 'windy'],
    compatibleStyleSlugs: ['workwear', 'vintage', 'casual'],
    layeringRole: 'outer',
  },
  {
    id: 'gar_leather_biker_black',
    name: 'Cropped Calfskin Leather Jacket',
    slug: 'cropped-leather-biker-black',
    category: 'outerwear',
    subcategory: 'leather-jacket',
    fit: 'boxy',
    silhouette: 'cropped-waist-broad-shoulder',
    length: 'cropped',
    color: { name: 'jet-black', hex: '#0A0A0A', tone: 'neutral', isBaseColor: true },
    material: 'full-grain oiled calfskin',
    pattern: 'solid',
    formality: 3,
    seasons: ['spring', 'fall'],
    compatibleWeather: ['cool', 'windy'],
    compatibleStyleSlugs: ['streetwear', 'vintage', 'minimal', 'experimental'],
    layeringRole: 'outer',
  },
  {
    id: 'gar_trench_coat_khaki',
    name: 'Belted Gabardine Trench Coat',
    slug: 'gabardine-trench-khaki',
    category: 'outerwear',
    subcategory: 'trench',
    fit: 'oversized',
    silhouette: 'fluid-raglan-longline',
    length: 'extended',
    color: { name: 'sand-khaki', hex: '#C2B280', tone: 'neutral', isBaseColor: true },
    material: 'weatherproof cotton gabardine',
    pattern: 'solid',
    formality: 3,
    seasons: ['spring', 'fall'],
    compatibleWeather: ['rainy', 'windy', 'mild', 'cool'],
    compatibleStyleSlugs: ['dark-academia', 'korean-minimal', 'minimal', 'smart-casual'],
    layeringRole: 'outer',
  },
  {
    id: 'gar_tech_shell_black',
    name: '3-Layer Weatherproof Technical Shell',
    slug: 'tech-shell-black',
    category: 'outerwear',
    subcategory: 'jacket',
    fit: 'tailored',
    silhouette: 'articulated-ergonomic',
    length: 'regular',
    color: { name: 'graphite-black', hex: '#1C1C1C', tone: 'neutral', isBaseColor: true },
    material: 'waterproof breathable membrane',
    pattern: 'solid',
    formality: 2,
    seasons: ['all-season'],
    compatibleWeather: ['rainy', 'windy', 'cold', 'cool'],
    compatibleStyleSlugs: ['techwear', 'minimal', 'streetwear'],
    layeringRole: 'outer',
  },
  {
    id: 'gar_formal_tux_jacket',
    name: 'Satin Peak-Lapel Dinner Jacket',
    slug: 'dinner-jacket-midnight-navy',
    category: 'outerwear',
    subcategory: 'tuxedo-jacket',
    fit: 'tailored',
    silhouette: 'sculpted-waist-canvassed',
    length: 'regular',
    color: { name: 'midnight-navy', hex: '#191970', tone: 'neutral', isBaseColor: true },
    material: 'Barathea wool with silk grosgrain lapels',
    pattern: 'solid',
    formality: 5,
    seasons: ['all-season'],
    compatibleWeather: ['mild', 'cool'],
    compatibleStyleSlugs: ['formal'],
    layeringRole: 'outer',
  },

  // --- BOTTOMS ---
  {
    id: 'gar_wide_trousers_black',
    name: 'Double-Pleated Wide-Leg Trousers',
    slug: 'wide-pleated-trousers-black',
    category: 'bottom',
    subcategory: 'trousers',
    fit: 'relaxed',
    silhouette: 'high-rise-wide-straight-drape',
    length: 'full-break',
    color: { name: 'pitch-black', hex: '#111111', tone: 'neutral', isBaseColor: true },
    material: 'wool gabardine blend',
    pattern: 'solid',
    formality: 3,
    seasons: ['all-season'],
    compatibleWeather: ['mild', 'cool', 'warm'],
    compatibleStyleSlugs: ['korean-minimal', 'minimal', 'smart-casual', 'dark-academia'],
    layeringRole: 'standalone',
  },
  {
    id: 'gar_raw_denim_indigo',
    name: 'Straight-Leg 14oz Selvedge Denim',
    slug: 'selvedge-denim-raw-indigo',
    category: 'bottom',
    subcategory: 'jeans',
    fit: 'regular',
    silhouette: 'mid-rise-straight-leg',
    length: 'regular',
    color: { name: 'raw-indigo', hex: '#1F2440', tone: 'earth', isBaseColor: false },
    material: '14oz Japanese selvedge denim',
    pattern: 'solid',
    formality: 2,
    seasons: ['all-season'],
    compatibleWeather: ['cool', 'mild', 'cold'],
    compatibleStyleSlugs: ['workwear', 'vintage', 'smart-casual', 'casual'],
    layeringRole: 'standalone',
  },
  {
    id: 'gar_tailored_slacks_charcoal',
    name: 'Flat-Front Tailored Wool Slacks',
    slug: 'tailored-slacks-charcoal',
    category: 'bottom',
    subcategory: 'trousers',
    fit: 'tailored',
    silhouette: 'clean-taper-no-break',
    length: 'ankle',
    color: { name: 'charcoal', hex: '#333333', tone: 'neutral', isBaseColor: true },
    material: '100% Super 120s wool',
    pattern: 'solid',
    formality: 4,
    seasons: ['all-season'],
    compatibleWeather: ['mild', 'cool', 'cold'],
    compatibleStyleSlugs: ['formal', 'smart-casual', 'old-money'],
    layeringRole: 'standalone',
  },
  {
    id: 'gar_carpenter_pant_canvas',
    name: 'Relaxed Double-Knee Carpenter Pants',
    slug: 'double-knee-carpenter-tan',
    category: 'bottom',
    subcategory: 'pants',
    fit: 'relaxed',
    silhouette: 'straight-rugged-roomy',
    length: 'regular',
    color: { name: 'duck-tan', hex: '#C29B38', tone: 'earth', isBaseColor: false },
    material: 'heavyweight washed canvas',
    pattern: 'solid',
    formality: 1,
    seasons: ['all-season'],
    compatibleWeather: ['mild', 'cool', 'cold'],
    compatibleStyleSlugs: ['streetwear', 'workwear', 'vintage'],
    layeringRole: 'standalone',
  },
  {
    id: 'gar_corduroy_trousers_olive',
    name: 'Wide-Wale Pleated Corduroy Trousers',
    slug: 'corduroy-trousers-olive',
    category: 'bottom',
    subcategory: 'trousers',
    fit: 'relaxed',
    silhouette: 'relaxed-taper',
    length: 'regular',
    color: { name: 'olive-green', hex: '#4B5320', tone: 'earth', isBaseColor: false },
    material: '8-wale thick cotton corduroy',
    pattern: 'textured-weave',
    formality: 3,
    seasons: ['fall', 'winter'],
    compatibleWeather: ['cold', 'cool'],
    compatibleStyleSlugs: ['dark-academia', 'vintage', 'smart-casual'],
    layeringRole: 'standalone',
  },
  {
    id: 'gar_cargo_pants_black',
    name: 'Articulated Technical Cargo Pants',
    slug: 'articulated-cargos-black',
    category: 'bottom',
    subcategory: 'cargo',
    fit: 'relaxed',
    silhouette: 'tapered-cuff-functional-gusset',
    length: 'ankle',
    color: { name: 'deep-black', hex: '#0B0B0B', tone: 'neutral', isBaseColor: true },
    material: 'water-repellent Schoeller dryskin',
    pattern: 'solid',
    formality: 2,
    seasons: ['all-season'],
    compatibleWeather: ['windy', 'rainy', 'cool', 'mild'],
    compatibleStyleSlugs: ['techwear', 'streetwear', 'experimental'],
    layeringRole: 'standalone',
  },
  {
    id: 'gar_linen_drawstring_ecru',
    name: 'Relaxed Linen Drawstring Trousers',
    slug: 'linen-trousers-ecru',
    category: 'bottom',
    subcategory: 'trousers',
    fit: 'relaxed',
    silhouette: 'airy-flowing-wide-leg',
    length: 'regular',
    color: { name: 'ecru', hex: '#F5F5DC', tone: 'neutral', isBaseColor: true },
    material: '100% Belgian washed linen',
    pattern: 'solid',
    formality: 2,
    seasons: ['summer', 'spring'],
    compatibleWeather: ['hot', 'warm'],
    compatibleStyleSlugs: ['korean-minimal', 'old-money', 'casual'],
    layeringRole: 'standalone',
  },

  // --- FOOTWEAR ---
  {
    id: 'gar_minimal_sneaker_white',
    name: 'Minimal Calfskin Low-Top Sneakers',
    slug: 'minimal-leather-sneaker-white',
    category: 'footwear',
    subcategory: 'sneakers',
    fit: 'regular',
    silhouette: 'sleek-monolithic-cupsole',
    color: { name: 'pure-white', hex: '#FFFFFF', tone: 'neutral', isBaseColor: true },
    material: 'Italian Nappa leather, Margom rubber sole',
    pattern: 'solid',
    formality: 2,
    seasons: ['all-season'],
    compatibleWeather: ['mild', 'warm', 'cool'],
    compatibleStyleSlugs: ['minimal', 'smart-casual', 'korean-minimal', 'casual'],
    layeringRole: 'standalone',
  },
  {
    id: 'gar_chunky_derbies_black',
    name: 'Commando-Sole Leather Derbies',
    slug: 'chunky-derbies-black',
    category: 'footwear',
    subcategory: 'derbies',
    fit: 'regular',
    silhouette: 'volumetric-rounded-toe',
    color: { name: 'polished-black', hex: '#050505', tone: 'neutral', isBaseColor: true },
    material: 'polished binder calf leather, Vibram lug sole',
    pattern: 'solid',
    formality: 3,
    seasons: ['all-season'],
    compatibleWeather: ['rainy', 'cool', 'cold', 'mild'],
    compatibleStyleSlugs: ['korean-minimal', 'dark-academia', 'minimal', 'experimental'],
    layeringRole: 'standalone',
  },
  {
    id: 'gar_penny_loafer_burgundy',
    name: 'Cordovan Penny Loafers',
    slug: 'penny-loafer-burgundy',
    category: 'footwear',
    subcategory: 'loafers',
    fit: 'regular',
    silhouette: 'classic-almond-toe-leather-sole',
    color: { name: 'deep-burgundy', hex: '#800020', tone: 'earth', isBaseColor: false },
    material: 'Horween shell cordovan',
    pattern: 'solid',
    formality: 4,
    seasons: ['spring', 'summer', 'fall'],
    compatibleWeather: ['mild', 'warm', 'cool'],
    compatibleStyleSlugs: ['old-money', 'smart-casual', 'dark-academia'],
    layeringRole: 'standalone',
  },
  {
    id: 'gar_chelsea_boot_suede_tobacco',
    name: 'Tobacco Suede Chelsea Boots',
    slug: 'chelsea-boots-suede-tobacco',
    category: 'footwear',
    subcategory: 'boots',
    fit: 'slim',
    silhouette: 'tapered-sleek-shaft',
    color: { name: 'tobacco-brown', hex: '#71523B', tone: 'earth', isBaseColor: false },
    material: 'waxed repello suede, crepe sole',
    pattern: 'solid',
    formality: 3,
    seasons: ['fall', 'winter', 'spring'],
    compatibleWeather: ['cool', 'cold', 'mild'],
    compatibleStyleSlugs: ['smart-casual', 'minimal', 'vintage'],
    layeringRole: 'standalone',
  },
  {
    id: 'gar_retro_court_sneaker',
    name: 'Vintage Suede & Mesh Court Trainers',
    slug: 'retro-court-trainers',
    category: 'footwear',
    subcategory: 'sneakers',
    fit: 'regular',
    silhouette: 'low-profile-gum-sole',
    color: { name: 'vintage-grey-cream', hex: '#DCDCDC', tone: 'neutral', isBaseColor: true },
    material: 'split suede, nylon mesh, gum rubber',
    pattern: 'solid',
    formality: 1,
    seasons: ['all-season'],
    compatibleWeather: ['warm', 'mild', 'cool'],
    compatibleStyleSlugs: ['streetwear', 'vintage', 'casual', 'korean-minimal'],
    layeringRole: 'standalone',
  },
  {
    id: 'gar_service_boots_brown',
    name: 'Goodyear-Welted Service Boots',
    slug: 'service-boots-brown',
    category: 'footwear',
    subcategory: 'boots',
    fit: 'regular',
    silhouette: 'rugged-cap-toe',
    color: { name: 'walnut-brown', hex: '#5C4033', tone: 'earth', isBaseColor: false },
    material: 'chromexcel leather, Dainite studded sole',
    pattern: 'solid',
    formality: 2,
    seasons: ['fall', 'winter', 'spring'],
    compatibleWeather: ['cold', 'cool', 'rainy'],
    compatibleStyleSlugs: ['workwear', 'vintage', 'dark-academia'],
    layeringRole: 'standalone',
  },
  {
    id: 'gar_formal_oxford_black',
    name: 'Cap-Toe Wholecut Oxford Shoes',
    slug: 'formal-captoe-oxford-black',
    category: 'footwear',
    subcategory: 'dress-shoes',
    fit: 'tailored',
    silhouette: 'razor-sleek-closed-lacing',
    color: { name: 'mirror-black', hex: '#000000', tone: 'neutral', isBaseColor: true },
    material: 'French box calf, oak-bark tanned leather sole',
    pattern: 'solid',
    formality: 5,
    seasons: ['all-season'],
    compatibleWeather: ['mild', 'cool', 'warm'],
    compatibleStyleSlugs: ['formal', 'old-money'],
    layeringRole: 'standalone',
  },

  // --- ACCESSORIES ---
  {
    id: 'gar_leather_tote_black',
    name: 'Structured Architectural Leather Tote',
    slug: 'architectural-leather-tote',
    category: 'accessory',
    subcategory: 'bag',
    fit: 'regular',
    silhouette: 'geometric-minimal-tote',
    color: { name: 'matte-black', hex: '#141414', tone: 'neutral', isBaseColor: true },
    material: 'vegetable-tanned full-grain leather',
    pattern: 'solid',
    formality: 3,
    seasons: ['all-season'],
    compatibleWeather: ['all-weather' as any],
    compatibleStyleSlugs: ['minimal', 'korean-minimal', 'smart-casual'],
    layeringRole: 'standalone',
  },
  {
    id: 'gar_silver_signet_ring',
    name: 'Brushed Sterling Silver Signet Ring',
    slug: 'silver-signet-ring',
    category: 'accessory',
    subcategory: 'jewelry',
    fit: 'regular',
    silhouette: 'cushion-bevel-signet',
    color: { name: 'silver', hex: '#C0C0C0', tone: 'cool', isBaseColor: false },
    material: '925 sterling silver',
    pattern: 'solid',
    formality: 3,
    seasons: ['all-season'],
    compatibleWeather: ['all-weather' as any],
    compatibleStyleSlugs: ['old-money', 'minimal', 'streetwear', 'dark-academia'],
    layeringRole: 'standalone',
  },
  {
    id: 'gar_wool_scarf_charcoal',
    name: 'Fringed Lambswool Scarf',
    slug: 'lambswool-scarf-charcoal',
    category: 'accessory',
    subcategory: 'scarf',
    fit: 'regular',
    silhouette: 'long-drape',
    color: { name: 'charcoal-melange', hex: '#4A4A4A', tone: 'neutral', isBaseColor: true },
    material: '100% Scottish lambswool',
    pattern: 'solid',
    formality: 3,
    seasons: ['fall', 'winter'],
    compatibleWeather: ['cold', 'cool', 'windy'],
    compatibleStyleSlugs: ['minimal', 'dark-academia', 'smart-casual', 'old-money'],
    layeringRole: 'outer',
  },
];
