import { HairStyle } from '../domain/grooming';

export const HAIRSTYLES: HairStyle[] = [
  {
    id: 'hair_textured_crop',
    name: 'Textured French Crop',
    slug: 'textured-crop',
    description:
      'Short forward fringe with textured crown layers and a clean low-to-mid fade on the sides. Accentuates masculine bone structure without high maintenance.',
    targetLength: 'short',
    compatibleTextures: ['straight', 'wavy', 'curly'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'square', 'heart', 'diamond'],
    incompatibleFaceShapes: ['round'], // can accentuate roundness if fringe is too blunt
    maintenance: 'minimal',
    stylingDifficulty: 'easy',
    formalityRange: [1, 4],
    compatibleStyleSlugs: ['minimal', 'streetwear', 'korean-minimal', 'smart-casual'],
    silhouetteCharacter: 'tight',
    visualTags: ['fringe', 'faded', 'textured', 'contemporary'],
    stylingTips: [
      'Apply matte styling powder or clay into damp or dry hair',
      'Pinch sections forward to enhance natural piecey separation',
    ],
  },
  {
    id: 'hair_classic_side_part',
    name: 'Classic Tapered Side Part',
    slug: 'classic-side-part',
    description:
      'Timeless gentleman’s silhouette with defined part line, scissor-tapered temples, and disciplined combed cadence.',
    targetLength: 'short',
    compatibleTextures: ['straight', 'wavy'],
    compatibleDensities: ['medium', 'high', 'low'],
    compatibleFaceShapes: ['oval', 'square', 'round', 'rectangle'],
    maintenance: 'moderate',
    stylingDifficulty: 'moderate',
    formalityRange: [3, 5],
    compatibleStyleSlugs: ['old-money', 'formal', 'smart-casual'],
    silhouetteCharacter: 'balanced',
    visualTags: ['tailored', 'executive', 'timeless', 'heritage'],
    stylingTips: [
      'Locate natural cowlick or off-center parting line',
      'Comb through using light pomade or styling cream with low sheen',
    ],
  },
  {
    id: 'hair_middle_part_curtains',
    name: 'Fluid Middle Part (Curtains)',
    slug: 'middle-part-curtains',
    description:
      'Flowing medium-length partition framing cheekbones with soft natural taper toward the nape. Iconic Korean editorial aesthetic.',
    targetLength: 'medium',
    compatibleTextures: ['straight', 'wavy'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'diamond', 'triangle', 'square'],
    incompatibleFaceShapes: ['round'],
    maintenance: 'moderate',
    stylingDifficulty: 'moderate',
    formalityRange: [2, 4],
    compatibleStyleSlugs: ['korean-minimal', 'minimal', 'vintage', 'dark-academia'],
    silhouetteCharacter: 'flowing',
    visualTags: ['curtains', 'flow', 'editorial', 'korean'],
    stylingTips: [
      'Blow-dry roots upward at the center part to build natural lift',
      'Seal ends with lightweight argan oil or airy paste',
    ],
  },
  {
    id: 'hair_tapered_buzz',
    name: 'Architectural Buzz Cut',
    slug: 'tapered-buzz',
    description:
      'Ultra-clean uniform clip with razor-precise temple fade and crisp hairline edges. Spotlights strong jawline and facial geometry.',
    targetLength: 'buzz',
    compatibleTextures: ['straight', 'wavy', 'curly', 'coily'],
    compatibleDensities: ['high', 'medium'],
    compatibleFaceShapes: ['oval', 'square', 'diamond'],
    incompatibleFaceShapes: ['round', 'rectangle'],
    maintenance: 'minimal',
    stylingDifficulty: 'easy',
    formalityRange: [1, 4],
    compatibleStyleSlugs: ['minimal', 'techwear', 'streetwear', 'experimental'],
    silhouetteCharacter: 'tight',
    visualTags: ['buzz', 'military', 'sculptural', 'zero-styling'],
    stylingTips: [
      'Zero daily styling required',
      'Keep scalp hydrated with lightweight botanical oil',
    ],
  },
  {
    id: 'hair_wavy_mod_cut',
    name: 'Wavy Shaggy Mod Cut',
    slug: 'wavy-mod-cut',
    description:
      'Layered vintage shag with textured perimeter over the ears and soft brow-skimming fringe. Rich indie patina.',
    targetLength: 'medium',
    compatibleTextures: ['wavy', 'curly'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'rectangle', 'heart', 'diamond'],
    maintenance: 'minimal',
    stylingDifficulty: 'easy',
    formalityRange: [1, 3],
    compatibleStyleSlugs: ['vintage', 'dark-academia', 'casual'],
    silhouetteCharacter: 'voluminous',
    visualTags: ['shag', 'wavy', 'patina', 'indie'],
    stylingTips: [
      'Air dry with sea salt spray for lived-in wavy definition',
      'Scrunch gently; avoid stiff gels or high heat',
    ],
  },
  {
    id: 'hair_textured_quiff',
    name: 'Deconstructed Quiff',
    slug: 'textured-quiff',
    description:
      'High-volume frontal upward sweep with textured separation and soft tapered sides. Adds vertical balance to compact faces.',
    targetLength: 'medium',
    compatibleTextures: ['straight', 'wavy'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['round', 'square', 'oval'],
    incompatibleFaceShapes: ['rectangle'], // can over-elongate long faces
    maintenance: 'moderate',
    stylingDifficulty: 'moderate',
    formalityRange: [2, 4],
    compatibleStyleSlugs: ['smart-casual', 'minimal', 'streetwear'],
    silhouetteCharacter: 'angular',
    visualTags: ['quiff', 'volume', 'uplift', 'modern'],
    stylingTips: [
      'Pre-style with sea salt spray while blow-drying backward and upward',
      'Finish with low-shine clay for flexible all-day hold',
    ],
  },
  {
    id: 'hair_slick_back_fade',
    name: 'Slick Back Undercut',
    slug: 'slick-back-fade',
    description:
      'Smooth backward sweep with high contrast skin taper or disconnected undercut. Sharp, aggressive elegance.',
    targetLength: 'medium',
    compatibleTextures: ['straight', 'wavy'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'square', 'diamond'],
    maintenance: 'high',
    stylingDifficulty: 'moderate',
    formalityRange: [3, 5],
    compatibleStyleSlugs: ['formal', 'minimal', 'techwear'],
    silhouetteCharacter: 'tight',
    visualTags: ['slick', 'undercut', 'sleek', 'bold'],
    stylingTips: [
      'Comb backward through damp strands with water-soluble pomade',
      'Ensure side taper is serviced bi-weekly to maintain razor edge',
    ],
  },
  {
    id: 'hair_curly_fade_taper',
    name: 'Curly High Top Taper',
    slug: 'curly-taper',
    description:
      'Controlled spherical crown of defined curls balanced by a gradient temple and neck taper. Celebrates natural coiled spring.',
    targetLength: 'medium',
    compatibleTextures: ['curly', 'coily'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'round', 'square', 'heart'],
    maintenance: 'moderate',
    stylingDifficulty: 'moderate',
    formalityRange: [1, 4],
    compatibleStyleSlugs: ['streetwear', 'korean-minimal', 'smart-casual'],
    silhouetteCharacter: 'voluminous',
    visualTags: ['curls', 'taper', 'texture', 'natural'],
    stylingTips: [
      'Apply leave-in curl cream to wet curls and allow to diffuse',
      'Never brush dry curls to maintain defined ringlet structure',
    ],
  },
  {
    id: 'hair_shoulder_flow',
    name: 'Shoulder-Length Flow',
    slug: 'shoulder-length-flow',
    description:
      'Relaxed mid-chest or shoulder length cascading layers tucked effortlessly behind the ears. Free-spirited, editorial nonchalance.',
    targetLength: 'shoulder',
    compatibleTextures: ['wavy', 'curly', 'straight'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'square', 'diamond', 'rectangle'],
    maintenance: 'moderate',
    stylingDifficulty: 'easy',
    formalityRange: [1, 3],
    compatibleStyleSlugs: ['vintage', 'dark-academia', 'casual', 'experimental'],
    silhouetteCharacter: 'flowing',
    visualTags: ['long-hair', 'flow', 'tuck', 'relaxed'],
    stylingTips: [
      'Apply light smoothing serum mid-lengths to ends',
      'Tuck behind ear on one side to open up facial geometry',
    ],
  },
  {
    id: 'hair_ivy_league',
    name: 'Ivy League Crew Cut',
    slug: 'ivy-league-crew',
    description:
      'Refined crew cut with enough length at the front to part or brush to the side. Subtle collegiate pedigree.',
    targetLength: 'short',
    compatibleTextures: ['straight', 'wavy'],
    compatibleDensities: ['low', 'medium', 'high'],
    compatibleFaceShapes: ['oval', 'square', 'rectangle', 'round'],
    maintenance: 'minimal',
    stylingDifficulty: 'easy',
    formalityRange: [2, 5],
    compatibleStyleSlugs: ['old-money', 'smart-casual', 'formal'],
    silhouetteCharacter: 'balanced',
    visualTags: ['collegiate', 'preppy', 'neat', 'versatile'],
    stylingTips: [
      'Finger comb a nickel-sized amount of light wax through crown',
      'Angle front crest subtly upward and to the side',
    ],
  },
  {
    id: 'hair_wolf_cut',
    name: 'Architectural Wolf Cut',
    slug: 'wolf-cut',
    description:
      'Deconstructed mullet-shag hybrid with pronounced volume at crown, tapered choppy side-burns, and feathered nape drape.',
    targetLength: 'medium',
    compatibleTextures: ['wavy', 'straight'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'heart', 'diamond', 'rectangle'],
    maintenance: 'moderate',
    stylingDifficulty: 'moderate',
    formalityRange: [1, 3],
    compatibleStyleSlugs: ['experimental', 'korean-minimal', 'vintage', 'streetwear'],
    silhouetteCharacter: 'flowing',
    visualTags: ['shag', 'mullet', 'avant-garde', 'texture'],
    stylingTips: [
      'Layer dry texture spray into crown for volumetric lift',
      'Piece out nape tendrils with styling paste',
    ],
  },
  {
    id: 'hair_comb_over_low_fade',
    name: 'Modern Comb Over Fade',
    slug: 'comb-over-low-fade',
    description:
      'Directional diagonal comb over paired with a refined low skin drop fade. Bridges modern edge with boardroom polish.',
    targetLength: 'short',
    compatibleTextures: ['straight', 'wavy'],
    compatibleDensities: ['low', 'medium', 'high'],
    compatibleFaceShapes: ['round', 'oval', 'square'],
    maintenance: 'moderate',
    stylingDifficulty: 'moderate',
    formalityRange: [2, 5],
    compatibleStyleSlugs: ['smart-casual', 'formal', 'old-money'],
    silhouetteCharacter: 'balanced',
    visualTags: ['comb-over', 'fade', 'polished', 'clean'],
    stylingTips: [
      'Guide along natural growth pattern using wide-tooth comb',
      'Use matte paste to avoid greasy shine',
    ],
  },
  {
    id: 'hair_short_locs_taper',
    name: 'Short Sculpted Locs with Taper',
    slug: 'short-locs-taper',
    description:
      'Precision cylindrical locs sculpted at eyebrow level, flanked by sharp gradient temple and neck taper.',
    targetLength: 'short',
    compatibleTextures: ['coily', 'curly'],
    compatibleDensities: ['high', 'medium'],
    compatibleFaceShapes: ['oval', 'square', 'heart', 'round'],
    maintenance: 'moderate',
    stylingDifficulty: 'easy',
    formalityRange: [1, 4],
    compatibleStyleSlugs: ['streetwear', 'minimal', 'techwear', 'smart-casual'],
    silhouetteCharacter: 'angular',
    visualTags: ['locs', 'textured', 'fade', 'sculptural'],
    stylingTips: [
      'Maintain scalp nourishment with jojoba or tea tree oils',
      'Palm roll loc roots regularly for clean cylindrical integrity',
    ],
  },
  {
    id: 'hair_french_crop_blunt',
    name: 'Blunt Forward Crop',
    slug: 'blunt-crop',
    description:
      'Horizontal architectural fringe cut with zero taper at the brow, paired with skin-tight drop fade. High runway impact.',
    targetLength: 'short',
    compatibleTextures: ['straight', 'wavy'],
    compatibleDensities: ['high', 'medium'],
    compatibleFaceShapes: ['oval', 'rectangle', 'diamond'],
    incompatibleFaceShapes: ['square', 'round'], // clashes with wide jaw or round cheeks
    maintenance: 'high',
    stylingDifficulty: 'easy',
    formalityRange: [1, 4],
    compatibleStyleSlugs: ['techwear', 'minimal', 'experimental'],
    silhouetteCharacter: 'angular',
    visualTags: ['blunt-fringe', 'high-fashion', 'futuristic'],
    stylingTips: [
      'Blow-dry flat downwards with paddle brush',
      'Requires weekly perimeter trimmer maintenance to preserve line',
    ],
  },
  {
    id: 'hair_caesar_cut',
    name: 'Classic Caesar Cut',
    slug: 'caesar-cut',
    description:
      'Uniform horizontal short fringe with scissor-shortened sides. Subtle, historical simplicity that flatters receding temples.',
    targetLength: 'short',
    compatibleTextures: ['straight', 'wavy', 'curly'],
    compatibleDensities: ['low', 'medium', 'high'],
    compatibleFaceShapes: ['oval', 'rectangle', 'square'],
    maintenance: 'minimal',
    stylingDifficulty: 'easy',
    formalityRange: [1, 4],
    compatibleStyleSlugs: ['minimal', 'workwear', 'smart-casual'],
    silhouetteCharacter: 'tight',
    visualTags: ['caesar', 'understated', 'low-density-friendly'],
    stylingTips: [
      'Towel dry and comb forward with fingertip swipe of matte balm',
      'Ideal camouflage for maturing hairlines',
    ],
  },
  {
    id: 'hair_pompadour_classic',
    name: 'Executive Pompadour',
    slug: 'executive-pompadour',
    description:
      'Sweeping frontal roll with substantial height, brushed back at the sides into a tailored taper.',
    targetLength: 'medium',
    compatibleTextures: ['straight', 'wavy'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'round', 'square'],
    incompatibleFaceShapes: ['rectangle'],
    maintenance: 'high',
    stylingDifficulty: 'advanced',
    formalityRange: [3, 5],
    compatibleStyleSlugs: ['old-money', 'formal', 'vintage'],
    silhouetteCharacter: 'voluminous',
    visualTags: ['pompadour', 'retro', 'statuesque', 'statement'],
    stylingTips: [
      'Round brush blow-dry with root lifter is non-negotiable',
      'Finish with medium-hold pliable pomade',
    ],
  },
  {
    id: 'hair_man_bun_undercut',
    name: 'Architectural Knot with Undercut',
    slug: 'knot-undercut',
    description:
      'Long crown gathered into a disciplined compact knot at the occipital bone, anchored by clean faded temples and nape.',
    targetLength: 'long',
    compatibleTextures: ['straight', 'wavy', 'curly'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'square', 'diamond'],
    maintenance: 'moderate',
    stylingDifficulty: 'easy',
    formalityRange: [1, 3],
    compatibleStyleSlugs: ['techwear', 'minimal', 'experimental'],
    silhouetteCharacter: 'tight',
    visualTags: ['knot', 'top-knot', 'clean', 'editorial'],
    stylingTips: [
      'Gather hair when 90% dry using a snag-free elastic band',
      'Smooth flyaways with botanical pomade stick',
    ],
  },
  {
    id: 'hair_messy_surfer_waves',
    name: 'Textured Casual Waves',
    slug: 'textured-casual-waves',
    description:
      'Mid-length unforced waves with subtle layering that falls naturally around cheekbones and collar.',
    targetLength: 'medium',
    compatibleTextures: ['wavy', 'curly'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'square', 'heart', 'rectangle'],
    maintenance: 'minimal',
    stylingDifficulty: 'easy',
    formalityRange: [1, 3],
    compatibleStyleSlugs: ['casual', 'vintage', 'workwear'],
    silhouetteCharacter: 'flowing',
    visualTags: ['beach-waves', 'effortless', 'undone'],
    stylingTips: [
      'Apply curl defining lotion onto damp hair and let air-dry',
      'Avoid high-heat blow-dryers to prevent frizz',
    ],
  },
];
