import { HairStyle } from '../domain/grooming';

export const HAIRSTYLES: HairStyle[] = [
  // 1
  {
    id: 'hair_textured_crop',
    name: 'Textured French Crop',
    slug: 'textured-crop',
    description:
      'Short forward fringe with textured crown layers and a clean low-to-mid fade on the sides. Accentuates bone structure without high daily maintenance.',
    targetLength: 'short',
    compatibleTextures: ['straight', 'wavy', 'curly'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'square', 'heart', 'diamond'],
    incompatibleFaceShapes: [], // Soft signal only: no hard incompatible face shapes
    maintenance: 'minimal',
    stylingDifficulty: 'easy',
    formalityRange: [1, 4],
    compatibleStyleSlugs: ['minimal', 'streetwear', 'korean-minimal', 'smart-casual'],
    silhouetteCharacter: 'tight',
    visualTags: ['fringe', 'faded', 'textured', 'contemporary'],
    stylingTips: [
      'Apply matte styling powder or clay into damp or dry hair',
      'Pinch sections forward to enhance natural piecey separation',
    ],
    genderCoding: 'androgynous',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 2
  {
    id: 'hair_classic_side_part',
    name: 'Classic Tapered Side Part',
    slug: 'classic-side-part',
    description:
      'Timeless gentleman’s silhouette with defined part line, scissor-tapered temples, and disciplined combed cadence.',
    targetLength: 'short',
    compatibleTextures: ['straight', 'wavy'],
    compatibleDensities: ['medium', 'high', 'low'],
    compatibleFaceShapes: ['oval', 'square', 'round', 'rectangle'],
    maintenance: 'moderate',
    stylingDifficulty: 'moderate',
    formalityRange: [3, 5],
    compatibleStyleSlugs: ['old-money', 'formal', 'smart-casual'],
    silhouetteCharacter: 'balanced',
    visualTags: ['tailored', 'executive', 'timeless', 'heritage'],
    stylingTips: [
      'Locate natural cowlick or off-center parting line',
      'Comb through using light pomade or styling cream with low sheen',
    ],
    genderCoding: 'masculine',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 3
  {
    id: 'hair_middle_part_curtains',
    name: 'Fluid Middle Part (Curtains)',
    slug: 'middle-part-curtains',
    description:
      'Flowing medium-length partition framing cheekbones with soft natural taper toward the nape. Iconic Korean and 90s editorial aesthetic.',
    targetLength: 'medium',
    compatibleTextures: ['straight', 'wavy'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'diamond', 'triangle', 'square', 'heart'],
    maintenance: 'moderate',
    stylingDifficulty: 'moderate',
    formalityRange: [2, 4],
    compatibleStyleSlugs: ['korean-minimal', 'minimal', 'vintage', 'dark-academia'],
    silhouetteCharacter: 'flowing',
    visualTags: ['curtains', 'flow', 'editorial', 'korean'],
    stylingTips: [
      'Blow-dry roots upward at the center part to build natural lift',
      'Seal ends with lightweight argan oil or airy paste',
    ],
    genderCoding: 'androgynous',
    timelessOrTrend: 'TREND',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 4
  {
    id: 'hair_tapered_buzz',
    name: 'Architectural Buzz Cut',
    slug: 'tapered-buzz',
    description:
      'Uniform clip with razor-precise temple fade and crisp hairline edges. Spotlights facial bone structure with zero daily effort.',
    targetLength: 'buzz',
    compatibleTextures: ['straight', 'wavy', 'curly', 'coily'],
    compatibleDensities: ['high', 'medium'],
    compatibleFaceShapes: ['oval', 'square', 'diamond', 'rectangle'],
    maintenance: 'minimal',
    stylingDifficulty: 'easy',
    formalityRange: [1, 4],
    compatibleStyleSlugs: ['minimal', 'techwear', 'streetwear', 'experimental'],
    silhouetteCharacter: 'tight',
    visualTags: ['buzz', 'military', 'sculptural', 'zero-styling'],
    stylingTips: [
      'Zero daily styling required',
      'Keep scalp hydrated with lightweight botanical oil',
    ],
    genderCoding: 'androgynous',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 5
  {
    id: 'hair_wavy_mod_cut',
    name: 'Wavy Shaggy Mod Cut',
    slug: 'wavy-mod-cut',
    description:
      'Layered vintage shag with textured perimeter over the ears and soft brow-skimming fringe. Rich indie patina.',
    targetLength: 'medium',
    compatibleTextures: ['wavy', 'curly'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'rectangle', 'heart', 'diamond'],
    maintenance: 'minimal',
    stylingDifficulty: 'easy',
    formalityRange: [1, 3],
    compatibleStyleSlugs: ['vintage', 'dark-academia', 'casual'],
    silhouetteCharacter: 'voluminous',
    visualTags: ['shag', 'wavy', 'patina', 'indie'],
    stylingTips: [
      'Air dry with sea salt spray for lived-in wavy definition',
      'Scrunch gently; avoid stiff gels or high heat',
    ],
    genderCoding: 'androgynous',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 6
  {
    id: 'hair_textured_quiff',
    name: 'Deconstructed Quiff',
    slug: 'textured-quiff',
    description:
      'Upward sweep with textured separation and soft tapered sides. Adds vertical balance to facial geometry.',
    targetLength: 'medium',
    compatibleTextures: ['straight', 'wavy'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['round', 'square', 'oval'],
    maintenance: 'moderate',
    stylingDifficulty: 'moderate',
    formalityRange: [2, 4],
    compatibleStyleSlugs: ['smart-casual', 'minimal', 'streetwear'],
    silhouetteCharacter: 'angular',
    visualTags: ['quiff', 'volume', 'uplift', 'modern'],
    stylingTips: [
      'Pre-style with sea salt spray while blow-drying backward and upward',
      'Finish with low-shine clay for flexible all-day hold',
    ],
    genderCoding: 'masculine',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 7
  {
    id: 'hair_slick_back_fade',
    name: 'Slick Back Undercut',
    slug: 'slick-back-fade',
    description:
      'Smooth backward sweep with high contrast skin taper or disconnected undercut. Sharp, disciplined elegance.',
    targetLength: 'medium',
    compatibleTextures: ['straight', 'wavy'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'square', 'diamond'],
    maintenance: 'high',
    stylingDifficulty: 'moderate',
    formalityRange: [3, 5],
    compatibleStyleSlugs: ['formal', 'minimal', 'techwear'],
    silhouetteCharacter: 'tight',
    visualTags: ['slick', 'undercut', 'sleek', 'bold'],
    stylingTips: [
      'Comb backward through damp strands with water-soluble pomade',
      'Ensure side taper is serviced bi-weekly to maintain clean edge',
    ],
    genderCoding: 'masculine',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 8
  {
    id: 'hair_curly_fade_taper',
    name: 'Curly High Top Taper',
    slug: 'curly-taper',
    description:
      'Controlled spherical crown of defined curls balanced by gradient temple and neck taper. Celebrates natural coiled texture.',
    targetLength: 'medium',
    compatibleTextures: ['curly', 'coily'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'round', 'square', 'heart'],
    maintenance: 'moderate',
    stylingDifficulty: 'moderate',
    formalityRange: [1, 4],
    compatibleStyleSlugs: ['streetwear', 'korean-minimal', 'smart-casual'],
    silhouetteCharacter: 'voluminous',
    visualTags: ['curls', 'taper', 'texture', 'natural'],
    stylingTips: [
      'Apply leave-in curl cream to wet curls and allow to diffuse',
      'Never brush dry curls to maintain defined spiral structure',
    ],
    genderCoding: 'androgynous',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 9
  {
    id: 'hair_shoulder_flow',
    name: 'Shoulder-Length Flow',
    slug: 'shoulder-length-flow',
    description:
      'Cascading natural layers tucked behind the ears. Free-spirited, editorial nonchalance.',
    targetLength: 'shoulder',
    compatibleTextures: ['wavy', 'curly', 'straight'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'square', 'diamond', 'rectangle'],
    maintenance: 'moderate',
    stylingDifficulty: 'easy',
    formalityRange: [1, 3],
    compatibleStyleSlugs: ['vintage', 'dark-academia', 'casual', 'experimental'],
    silhouetteCharacter: 'flowing',
    visualTags: ['long-hair', 'flow', 'tuck', 'relaxed'],
    stylingTips: [
      'Apply light smoothing serum mid-lengths to ends',
      'Tuck behind ear on one side to open up facial geometry',
    ],
    genderCoding: 'androgynous',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 10
  {
    id: 'hair_ivy_league',
    name: 'Ivy League Crew Cut',
    slug: 'ivy-league-crew',
    description:
      'Refined crew cut with enough length at the front to part or brush to the side. Subtle collegiate pedigree.',
    targetLength: 'short',
    compatibleTextures: ['straight', 'wavy'],
    compatibleDensities: ['low', 'medium', 'high'],
    compatibleFaceShapes: ['oval', 'square', 'rectangle', 'round'],
    maintenance: 'minimal',
    stylingDifficulty: 'easy',
    formalityRange: [2, 5],
    compatibleStyleSlugs: ['old-money', 'smart-casual', 'formal'],
    silhouetteCharacter: 'balanced',
    visualTags: ['collegiate', 'preppy', 'neat', 'versatile'],
    stylingTips: [
      'Finger comb a nickel-sized amount of light wax through crown',
      'Angle front crest subtly upward and to the side',
    ],
    genderCoding: 'masculine',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 11
  {
    id: 'hair_wolf_cut',
    name: 'Architectural Wolf Cut',
    slug: 'wolf-cut',
    description:
      'Deconstructed mullet-shag hybrid with crown volume, tapered choppy sides, and feathered nape drape.',
    targetLength: 'medium',
    compatibleTextures: ['wavy', 'straight'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'heart', 'diamond', 'rectangle'],
    maintenance: 'moderate',
    stylingDifficulty: 'moderate',
    formalityRange: [1, 3],
    compatibleStyleSlugs: ['experimental', 'korean-minimal', 'vintage', 'streetwear'],
    silhouetteCharacter: 'flowing',
    visualTags: ['shag', 'mullet', 'avant-garde', 'texture'],
    stylingTips: [
      'Layer dry texture spray into crown for volumetric lift',
      'Piece out nape tendrils with styling paste',
    ],
    genderCoding: 'androgynous',
    timelessOrTrend: 'TREND',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 12
  {
    id: 'hair_comb_over_low_fade',
    name: 'Modern Comb Over Fade',
    slug: 'comb-over-low-fade',
    description:
      'Directional diagonal comb over paired with a refined low skin drop fade. Bridges modern edge with executive polish.',
    targetLength: 'short',
    compatibleTextures: ['straight', 'wavy'],
    compatibleDensities: ['low', 'medium', 'high'],
    compatibleFaceShapes: ['round', 'oval', 'square'],
    maintenance: 'moderate',
    stylingDifficulty: 'moderate',
    formalityRange: [2, 5],
    compatibleStyleSlugs: ['smart-casual', 'formal', 'old-money'],
    silhouetteCharacter: 'balanced',
    visualTags: ['comb-over', 'fade', 'polished', 'clean'],
    stylingTips: [
      'Guide along natural growth pattern using wide-tooth comb',
      'Use matte paste to avoid greasy shine',
    ],
    genderCoding: 'masculine',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 13 (Protective Style)
  {
    id: 'hair_short_locs_taper',
    name: 'Short Sculpted Locs with Taper',
    slug: 'short-locs-taper',
    description:
      'Precision cylindrical locs sculpted at brow level, flanked by sharp gradient temple and neck taper.',
    targetLength: 'short',
    compatibleTextures: ['coily', 'curly'],
    compatibleDensities: ['high', 'medium'],
    compatibleFaceShapes: ['oval', 'square', 'heart', 'round'],
    maintenance: 'moderate',
    stylingDifficulty: 'easy',
    formalityRange: [1, 4],
    compatibleStyleSlugs: ['streetwear', 'minimal', 'techwear', 'smart-casual'],
    silhouetteCharacter: 'angular',
    visualTags: ['locs', 'textured', 'fade', 'sculptural', 'protective'],
    stylingTips: [
      'Maintain scalp nourishment with jojoba or tea tree oils',
      'Palm roll loc roots regularly for clean cylindrical integrity',
    ],
    protectiveStyle: true,
    genderCoding: 'androgynous',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 14
  {
    id: 'hair_blunt_crop',
    name: 'Blunt Forward Crop',
    slug: 'blunt-crop',
    description:
      'Horizontal architectural fringe cut with zero taper at brow, paired with skin-tight drop fade. High runway impact.',
    targetLength: 'short',
    compatibleTextures: ['straight', 'wavy'],
    compatibleDensities: ['high', 'medium'],
    compatibleFaceShapes: ['oval', 'rectangle', 'diamond'],
    maintenance: 'high',
    stylingDifficulty: 'easy',
    formalityRange: [1, 4],
    compatibleStyleSlugs: ['techwear', 'minimal', 'experimental'],
    silhouetteCharacter: 'angular',
    visualTags: ['blunt-fringe', 'high-fashion', 'futuristic'],
    stylingTips: [
      'Blow-dry flat downwards with paddle brush',
      'Requires bi-weekly perimeter trimmer maintenance to preserve line',
    ],
    genderCoding: 'androgynous',
    timelessOrTrend: 'TREND',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 15
  {
    id: 'hair_caesar_cut',
    name: 'Classic Caesar Cut',
    slug: 'caesar-cut',
    description:
      'Uniform horizontal short fringe with scissor-shortened sides. Subtle historical simplicity that gracefully handles maturing hairlines.',
    targetLength: 'short',
    compatibleTextures: ['straight', 'wavy', 'curly'],
    compatibleDensities: ['low', 'medium', 'high'],
    compatibleFaceShapes: ['oval', 'rectangle', 'square'],
    maintenance: 'minimal',
    stylingDifficulty: 'easy',
    formalityRange: [1, 4],
    compatibleStyleSlugs: ['minimal', 'workwear', 'smart-casual'],
    silhouetteCharacter: 'tight',
    visualTags: ['caesar', 'understated', 'low-density-friendly'],
    stylingTips: [
      'Towel dry and comb forward with fingertip swipe of matte balm',
      'Ideal camouflage for maturing hairlines',
    ],
    genderCoding: 'masculine',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 16
  {
    id: 'hair_executive_pompadour',
    name: 'Executive Pompadour',
    slug: 'executive-pompadour',
    description:
      'Sweeping frontal roll with substantial height, brushed back at sides into a tailored taper.',
    targetLength: 'medium',
    compatibleTextures: ['straight', 'wavy'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'round', 'square'],
    maintenance: 'high',
    stylingDifficulty: 'advanced',
    formalityRange: [3, 5],
    compatibleStyleSlugs: ['old-money', 'formal', 'vintage'],
    silhouetteCharacter: 'voluminous',
    visualTags: ['pompadour', 'retro', 'statuesque', 'statement'],
    stylingTips: [
      'Round brush blow-dry with root lifter is non-negotiable',
      'Finish with medium-hold pliable pomade',
    ],
    genderCoding: 'masculine',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 17
  {
    id: 'hair_knot_undercut',
    name: 'Architectural Knot with Undercut',
    slug: 'knot-undercut',
    description:
      'Long crown gathered into a disciplined compact knot at occipital bone, anchored by clean faded temples and nape.',
    targetLength: 'long',
    compatibleTextures: ['straight', 'wavy', 'curly'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'square', 'diamond'],
    maintenance: 'moderate',
    stylingDifficulty: 'easy',
    formalityRange: [1, 3],
    compatibleStyleSlugs: ['techwear', 'minimal', 'experimental'],
    silhouetteCharacter: 'tight',
    visualTags: ['knot', 'top-knot', 'clean', 'editorial'],
    stylingTips: [
      'Gather hair when 90% dry using a snag-free elastic band',
      'Smooth flyaways with botanical pomade stick',
    ],
    genderCoding: 'androgynous',
    timelessOrTrend: 'TREND',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 18
  {
    id: 'hair_textured_casual_waves',
    name: 'Textured Casual Waves',
    slug: 'textured-casual-waves',
    description:
      'Mid-length unforced waves with subtle layering that falls naturally around cheekbones and collar.',
    targetLength: 'medium',
    compatibleTextures: ['wavy', 'curly'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'square', 'heart', 'rectangle'],
    maintenance: 'minimal',
    stylingDifficulty: 'easy',
    formalityRange: [1, 3],
    compatibleStyleSlugs: ['casual', 'vintage', 'workwear'],
    silhouetteCharacter: 'flowing',
    visualTags: ['beach-waves', 'effortless', 'undone'],
    stylingTips: [
      'Apply curl defining lotion onto damp hair and let air-dry',
      'Avoid high-heat blow-dryers to prevent frizz',
    ],
    genderCoding: 'androgynous',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 19 (Protective Style)
  {
    id: 'hair_box_braids_mid',
    name: 'Mid-Length Box Braids',
    slug: 'box-braids-mid',
    description:
      'Square-parted individual braids falling to collarbone level. Exceptional versatility with low daily maintenance.',
    targetLength: 'medium',
    compatibleTextures: ['coily', 'curly'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'round', 'square', 'heart', 'diamond'],
    maintenance: 'minimal',
    stylingDifficulty: 'easy',
    formalityRange: [1, 4],
    compatibleStyleSlugs: ['streetwear', 'minimal', 'smart-casual', 'vintage'],
    silhouetteCharacter: 'flowing',
    visualTags: ['braids', 'protective', 'versatile', 'clean'],
    stylingTips: [
      'Moisturize scalp with braid spray containing aloe and peppermint',
      'Sleep with satin bonnet to prevent friction frizz',
    ],
    protectiveStyle: true,
    genderCoding: 'androgynous',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 20 (Protective Style)
  {
    id: 'hair_cornrows_clean_taper',
    name: 'Geometric Cornrows with Taper',
    slug: 'cornrows-clean-taper',
    description:
      'Sleek scalp-braided linear cornrows leading backward, framed by razor-sharp temple and neckline taper.',
    targetLength: 'short',
    compatibleTextures: ['coily', 'curly'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'square', 'rectangle', 'diamond'],
    maintenance: 'minimal',
    stylingDifficulty: 'easy',
    formalityRange: [1, 4],
    compatibleStyleSlugs: ['streetwear', 'minimal', 'techwear', 'smart-casual'],
    silhouetteCharacter: 'tight',
    visualTags: ['cornrows', 'sculptural', 'taper', 'protective'],
    stylingTips: [
      'Keep edges nourished with lightweight castor oil serum',
      'Retouch edge taper every two weeks for geometric crispness',
    ],
    protectiveStyle: true,
    genderCoding: 'androgynous',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 21 (Protective Style)
  {
    id: 'hair_two_strand_twists',
    name: 'Defined Two-Strand Twists',
    slug: 'two-strand-twists',
    description:
      'Rope-twisted sections with defined ends and rich dimensional texture. Soft, organic drape with high moisture retention.',
    targetLength: 'short',
    compatibleTextures: ['coily', 'curly'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'round', 'heart', 'diamond'],
    maintenance: 'minimal',
    stylingDifficulty: 'easy',
    formalityRange: [1, 4],
    compatibleStyleSlugs: ['streetwear', 'korean-minimal', 'smart-casual', 'casual'],
    silhouetteCharacter: 'balanced',
    visualTags: ['twists', 'protective', 'natural-coils', 'tactile'],
    stylingTips: [
      'Twist wet using shea butter or curling custard for defined hold',
      'Can be untwisted after 1-2 weeks into a voluminous twist-out',
    ],
    protectiveStyle: true,
    genderCoding: 'androgynous',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 22
  {
    id: 'hair_afro_taper_fade',
    name: 'Sculpted Afro with Low Taper',
    slug: 'afro-taper-fade',
    description:
      'Rounded cloud silhouette of natural dense coils gently shaped with shears, grounded by low temple and nape skin fade.',
    targetLength: 'short',
    compatibleTextures: ['coily'],
    compatibleDensities: ['high', 'medium'],
    compatibleFaceShapes: ['oval', 'square', 'round', 'heart'],
    maintenance: 'moderate',
    stylingDifficulty: 'moderate',
    formalityRange: [1, 4],
    compatibleStyleSlugs: ['smart-casual', 'streetwear', 'minimal', 'vintage'],
    silhouetteCharacter: 'voluminous',
    visualTags: ['afro', 'natural', 'taper', 'heritage'],
    stylingTips: [
      'Pick out coils gently using wide wooden afro pick when damp',
      'Hydrate daily with water-based leave-in mist',
    ],
    genderCoding: 'androgynous',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 23
  {
    id: 'hair_classic_bob_blunt',
    name: 'Architectural Blunt Bob',
    slug: 'blunt-bob',
    description:
      'Razor-straight chin-length perimeter cut with crisp weight line and zero layering. High editorial geometry.',
    targetLength: 'medium',
    compatibleTextures: ['straight'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'heart', 'diamond'],
    maintenance: 'moderate',
    stylingDifficulty: 'moderate',
    formalityRange: [2, 5],
    compatibleStyleSlugs: ['minimal', 'korean-minimal', 'experimental', 'smart-casual'],
    silhouetteCharacter: 'angular',
    visualTags: ['bob', 'architectural', 'clean', 'editorial'],
    stylingTips: [
      'Flat iron with heat protector for glass-hair finish',
      'Trim every 4-6 weeks to preserve sharp horizontal perimeter',
    ],
    genderCoding: 'feminine',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 24
  {
    id: 'hair_layered_shag_long',
    name: 'Long Layered Shag with Curtain Bangs',
    slug: 'long-layered-shag',
    description:
      'Cascading feather-cut layers past collarbone paired with cheekbone-framing soft fringe. Effortless 70s rock aesthetic.',
    targetLength: 'long',
    compatibleTextures: ['wavy', 'curly', 'straight'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'square', 'rectangle', 'heart'],
    maintenance: 'moderate',
    stylingDifficulty: 'easy',
    formalityRange: [1, 4],
    compatibleStyleSlugs: ['vintage', 'dark-academia', 'casual', 'streetwear'],
    silhouetteCharacter: 'flowing',
    visualTags: ['shag', 'curtain-bangs', '70s', 'layered'],
    stylingTips: [
      'Diffuse naturally with sea salt spray for lived-in movement',
      'Blow-dry fringe forward then flick outwards with round brush',
    ],
    genderCoding: 'androgynous',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 25
  {
    id: 'hair_pixie_tapered',
    name: 'Sculpted Tapered Pixie',
    slug: 'tapered-pixie',
    description:
      'Close scissor-cut nape and sides with piecey textured crown layers sweeping forward or to the side. Crisp, confident minimalism.',
    targetLength: 'short',
    compatibleTextures: ['straight', 'wavy'],
    compatibleDensities: ['medium', 'high', 'low'],
    compatibleFaceShapes: ['oval', 'heart', 'square'],
    maintenance: 'moderate',
    stylingDifficulty: 'easy',
    formalityRange: [2, 5],
    compatibleStyleSlugs: ['minimal', 'smart-casual', 'old-money'],
    silhouetteCharacter: 'tight',
    visualTags: ['pixie', 'chic', 'minimal', 'sculpted'],
    stylingTips: [
      'Work fingertip of lightweight matte wax through dry crown',
      'Smooth sideburns flat against temples',
    ],
    genderCoding: 'feminine',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 26
  {
    id: 'hair_long_dreadlocks',
    name: 'Long Mature Dreadlocks',
    slug: 'long-mature-dreadlocks',
    description:
      'Chest-length mature uniform locs with natural cylindrical weight. Rich cultural heritage and statuesque presence.',
    targetLength: 'long',
    compatibleTextures: ['coily', 'curly'],
    compatibleDensities: ['high', 'medium'],
    compatibleFaceShapes: ['oval', 'square', 'diamond', 'rectangle'],
    maintenance: 'minimal',
    stylingDifficulty: 'easy',
    formalityRange: [1, 4],
    compatibleStyleSlugs: ['streetwear', 'vintage', 'workwear', 'experimental'],
    silhouetteCharacter: 'flowing',
    visualTags: ['locs', 'long', 'heritage', 'protective'],
    stylingTips: [
      'Wash bi-weekly with residue-free clarifying shampoo',
      'Air dry thoroughly to prevent moisture buildup in loc core',
    ],
    protectiveStyle: true,
    genderCoding: 'androgynous',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 27
  {
    id: 'hair_undercut_fade_long_top',
    name: 'Disconneced Undercut with Flow',
    slug: 'disconnected-undercut-flow',
    description:
      'Long scissor-cut top left flowing loosely over tight clippered sides and back. High visual contrast between sleek sides and textured crown.',
    targetLength: 'medium',
    compatibleTextures: ['straight', 'wavy'],
    compatibleDensities: ['high', 'medium'],
    compatibleFaceShapes: ['oval', 'square', 'diamond'],
    maintenance: 'high',
    stylingDifficulty: 'moderate',
    formalityRange: [1, 4],
    compatibleStyleSlugs: ['streetwear', 'techwear', 'minimal'],
    silhouetteCharacter: 'angular',
    visualTags: ['undercut', 'flow', 'contrast', 'bold'],
    stylingTips: [
      'Sweep top to preferred side with light styling cream',
      'Maintain clipper fade every 10-14 days',
    ],
    genderCoding: 'masculine',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 28
  {
    id: 'hair_french_crop_curly',
    name: 'Curly Fringe Crop with Low Drop Fade',
    slug: 'curly-fringe-crop',
    description:
      'Short forward curly cluster falling over forehead with low skin drop fade behind ears. Highly popular contemporary silhouette.',
    targetLength: 'short',
    compatibleTextures: ['curly', 'wavy'],
    compatibleDensities: ['medium', 'high'],
    compatibleFaceShapes: ['oval', 'diamond', 'heart', 'square'],
    maintenance: 'moderate',
    stylingDifficulty: 'easy',
    formalityRange: [1, 3],
    compatibleStyleSlugs: ['streetwear', 'korean-minimal', 'casual'],
    silhouetteCharacter: 'tight',
    visualTags: ['curly-fringe', 'drop-fade', 'youth', 'texture'],
    stylingTips: [
      'Scrunch curl mousse into damp top and let air dry',
      'Do not towel-rub harshly to preserve curl definition',
    ],
    genderCoding: 'androgynous',
    timelessOrTrend: 'TREND',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 29
  {
    id: 'hair_soft_side_swept_layers',
    name: 'Soft Side-Swept Medium Layers',
    slug: 'side-swept-layers',
    description:
      'Gentle diagonal sweep across forehead with soft scissor-cut taper over ears and nape. Understated academic poise.',
    targetLength: 'short',
    compatibleTextures: ['straight', 'wavy'],
    compatibleDensities: ['low', 'medium', 'high'],
    compatibleFaceShapes: ['oval', 'round', 'square', 'rectangle'],
    maintenance: 'minimal',
    stylingDifficulty: 'easy',
    formalityRange: [2, 5],
    compatibleStyleSlugs: ['smart-casual', 'old-money', 'dark-academia'],
    silhouetteCharacter: 'balanced',
    visualTags: ['side-swept', 'neat', 'classic', 'gentle'],
    stylingTips: [
      'Towel dry and comb diagonally with fingertips and light cream',
      'Very forgiving on days without styling product',
    ],
    genderCoding: 'androgynous',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  // 30
  {
    id: 'hair_coily_mini_fro_taper',
    name: 'Defined Coily Taper (Short Wash & Go)',
    slug: 'coily-mini-fro-taper',
    description:
      'Compact 1-2 inch coiled curls defined with hydrating custard, accented with soft graduated temple fade.',
    targetLength: 'short',
    compatibleTextures: ['coily', 'curly'],
    compatibleDensities: ['high', 'medium'],
    compatibleFaceShapes: ['oval', 'round', 'square', 'heart', 'diamond'],
    maintenance: 'minimal',
    stylingDifficulty: 'easy',
    formalityRange: [1, 4],
    compatibleStyleSlugs: ['minimal', 'smart-casual', 'korean-minimal', 'casual'],
    silhouetteCharacter: 'tight',
    visualTags: ['coils', 'natural', 'clean-taper', 'wash-and-go'],
    stylingTips: [
      'Apply curling jelly to soaking wet hair and shake gently',
      'Air dry or sit under hooded dryer for frizz-free spiral definition',
    ],
    genderCoding: 'androgynous',
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
];
