import { Occasion } from '../domain/context';

export const OCCASIONS: Occasion[] = [
  {
    id: 'occ_interview',
    slug: 'interview',
    name: 'Job Interview',
    category: 'professional',
    defaultFormality: 4,
    allowableFormalityRange: [3, 5],
    guidelines: [
      'Prioritize structured tailoring and restrained color discipline',
      'Ensure grooming is pristine, hair disciplined, and collar crisp',
      'Avoid loud logos, excessive jewelry, and casual sneakers',
    ],
    restrictedGarmentCategories: ['graphic-tees', 'distressed-denim', 'hoodies', 'shorts'],
    keyStyleAffinities: ['formal', 'smart-casual', 'old-money', 'minimal'],
  },
  {
    id: 'occ_office',
    slug: 'office',
    name: 'Modern Office / Workplace',
    category: 'professional',
    defaultFormality: 3,
    allowableFormalityRange: [2, 4],
    guidelines: [
      'Balance comfort and professional authority',
      'Knit polos, tailored trousers, clean derbies or minimal white sneakers',
      'Neutral and earth tones communicate competence and calm',
    ],
    restrictedGarmentCategories: ['athletic-shorts', 'flip-flops', 'loud-graphics'],
    keyStyleAffinities: ['smart-casual', 'minimal', 'korean-minimal'],
  },
  {
    id: 'occ_date',
    slug: 'date',
    name: 'Evening Date',
    category: 'evening',
    defaultFormality: 3,
    allowableFormalityRange: [2, 4],
    guidelines: [
      'Focus on tactile textures (merino, suede, brushed cotton) that invite closeness',
      'Silhouette should look intentional and flattering without looking over-stiff',
      'Elevate through dark palette anchoring (black, charcoal, deep navy, rich brown)',
    ],
    restrictedGarmentCategories: ['gym-wear', 'ill-fitting-basics'],
    keyStyleAffinities: ['smart-casual', 'minimal', 'korean-minimal', 'old-money'],
  },
  {
    id: 'occ_dinner',
    slug: 'dinner',
    name: 'Fine Dining / Dinner Party',
    category: 'evening',
    defaultFormality: 4,
    allowableFormalityRange: [3, 5],
    guidelines: [
      'Sophisticated layering, structured outerwear, and immaculate footwear',
      'Drape and fabric drape are paramount under warm ambient restaurant lighting',
    ],
    restrictedGarmentCategories: ['sweatpants', 'running-shoes'],
    keyStyleAffinities: ['minimal', 'smart-casual', 'old-money', 'formal'],
  },
  {
    id: 'occ_night_out',
    slug: 'night-out',
    name: 'Night Out / Lounge / Club',
    category: 'evening',
    defaultFormality: 2,
    allowableFormalityRange: [2, 4],
    guidelines: [
      'Embrace edge, contrast, and darker moody tones',
      'Strong silhouette: cropped leather jackets, relaxed wide trousers, or statement boots',
      'Jewelry and subtle accessories can take center stage',
    ],
    restrictedGarmentCategories: ['corporate-slacks', 'boring-polos'],
    keyStyleAffinities: ['streetwear', 'techwear', 'experimental', 'vintage', 'minimal'],
  },
  {
    id: 'occ_party',
    slug: 'party',
    name: 'Social Gathering / Party',
    category: 'social',
    defaultFormality: 2,
    allowableFormalityRange: [1, 3],
    guidelines: [
      'Expressive styling with conversation-starter silhouettes or textures',
      'High mobility and effortless self-assured presence',
    ],
    restrictedGarmentCategories: ['black-tie-tuxedo', 'work-suit'],
    keyStyleAffinities: ['streetwear', 'korean-minimal', 'vintage', 'casual'],
  },
  {
    id: 'occ_college',
    slug: 'college',
    name: 'University / College Campus',
    category: 'academic',
    defaultFormality: 2,
    allowableFormalityRange: [1, 3],
    guidelines: [
      'Comfort-driven layered casual with strong proportions',
      'Heavyweight hoodies under work jackets, relaxed denim, timeless sneakers',
    ],
    restrictedGarmentCategories: ['full-tuxedos', 'business-suits'],
    keyStyleAffinities: ['streetwear', 'workwear', 'korean-minimal', 'dark-academia', 'casual'],
  },
  {
    id: 'occ_wedding',
    slug: 'wedding',
    name: 'Wedding Guest',
    category: 'ceremony',
    defaultFormality: 4,
    allowableFormalityRange: [3, 5],
    guidelines: [
      'Honor ceremonial formality without overshadowing the hosts',
      'Never wear all-white; choose rich navy, charcoal, or refined earthy linen suits',
      'Pair with polished oxfords or dress loafers',
    ],
    restrictedGarmentCategories: ['casual-denim', 'sneakers', 't-shirts'],
    keyStyleAffinities: ['formal', 'old-money', 'smart-casual'],
  },
  {
    id: 'occ_casual_day',
    slug: 'casual-day',
    name: 'Weekend Casual / City Walk',
    category: 'casual',
    defaultFormality: 1,
    allowableFormalityRange: [1, 2],
    guidelines: [
      'Effortless silhouettes with high breathability and walkability',
      'Boxy cut tees, relaxed chinos, unbuttoned lightweight overshirts',
    ],
    restrictedGarmentCategories: ['rigid-suits', 'dress-shoes'],
    keyStyleAffinities: ['casual', 'korean-minimal', 'workwear', 'minimal'],
  },
  {
    id: 'occ_travel',
    slug: 'travel',
    name: 'Airport / Travel Transit',
    category: 'casual',
    defaultFormality: 2,
    allowableFormalityRange: [1, 3],
    guidelines: [
      'Wrinkle-resistant fabrics, functional layers for temperature shifts',
      'Easy slip-on footwear and ergonomic relaxed trousers',
    ],
    restrictedGarmentCategories: ['stiff-suits', 'impractical-footwear'],
    keyStyleAffinities: ['techwear', 'minimal', 'korean-minimal', 'casual'],
  },
];
