import { Occasion } from '../domain/context';

export const OCCASIONS: Occasion[] = [
  {
    id: 'occ_interview',
    slug: 'job-interview',
    name: 'Job Interview',
    category: 'professional',
    defaultFormality: 4,
    allowableFormalityRange: [3, 5],
    guidelines: [
      'Prioritize structured tailoring and restrained color discipline',
      'Ensure grooming is pristine, hair disciplined, and collar crisp',
      'Avoid loud logos, excessive jewelry, and casual sneakers',
    ],
    restrictedGarmentCategories: ['graphic-tees', 'distressed-denim', 'hoodies', 'shorts', 'sandals'],
    keyStyleAffinities: ['formal', 'smart-casual', 'old-money', 'minimal'],
    subParameters: ['corporate', 'creative', 'startup'],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'occ_office',
    slug: 'office',
    name: 'Modern Office / Workplace',
    category: 'professional',
    defaultFormality: 3,
    allowableFormalityRange: [2, 4],
    guidelines: [
      'Balance comfort and professional authority',
      'Knit polos, tailored trousers, clean derbies or minimal leather sneakers',
      'Neutral and earth tones communicate competence and calm',
    ],
    restrictedGarmentCategories: ['athletic-shorts', 'flip-flops', 'loud-graphics', 'tank-tops'],
    keyStyleAffinities: ['smart-casual', 'minimal', 'korean-minimal'],
    subParameters: ['corporate', 'creative', 'startup'],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'occ_casual_day',
    slug: 'casual',
    name: 'Everyday Casual / Weekend',
    category: 'casual',
    defaultFormality: 1,
    allowableFormalityRange: [1, 2],
    guidelines: [
      'Effortless silhouettes with high breathability and walkability',
      'Boxy cut tees, relaxed chinos, unbuttoned lightweight overshirts',
    ],
    restrictedGarmentCategories: ['rigid-suits', 'dress-shoes', 'tuxedos'],
    keyStyleAffinities: ['casual', 'korean-minimal', 'workwear', 'minimal'],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'occ_dinner',
    slug: 'dinner',
    name: 'Fine Dining / Dinner Party',
    category: 'evening',
    defaultFormality: 4,
    allowableFormalityRange: [3, 5],
    guidelines: [
      'Sophisticated layering, structured outerwear, and immaculate footwear',
      'Drape and fabric texture are paramount under warm ambient restaurant lighting',
    ],
    restrictedGarmentCategories: ['sweatpants', 'running-shoes', 'distressed-shorts', 'gym-wear'],
    keyStyleAffinities: ['minimal', 'smart-casual', 'old-money', 'formal'],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'occ_date',
    slug: 'date',
    name: 'Evening Date',
    category: 'evening',
    defaultFormality: 3,
    allowableFormalityRange: [2, 4],
    guidelines: [
      'Focus on tactile textures (merino, suede, brushed cotton) that invite closeness',
      'Silhouette should look intentional and well-proportioned without looking over-stiff',
      'Elevate through dark palette anchoring (black, charcoal, deep navy, rich brown)',
    ],
    restrictedGarmentCategories: ['gym-wear', 'ill-fitting-basics', 'flip-flops'],
    keyStyleAffinities: ['smart-casual', 'minimal', 'korean-minimal', 'old-money'],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'occ_night_out',
    slug: 'night-out',
    name: 'Night Out / Lounge / Club',
    category: 'evening',
    defaultFormality: 2,
    allowableFormalityRange: [2, 4],
    guidelines: [
      'Embrace edge, contrast, and darker moody tones',
      'Strong silhouette: cropped leather jackets, relaxed wide trousers, or statement boots',
      'Jewelry and subtle accessories can take center stage',
    ],
    restrictedGarmentCategories: ['corporate-slacks', 'boring-polos', 'gym-shorts'],
    keyStyleAffinities: ['streetwear', 'techwear', 'experimental', 'vintage', 'minimal'],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'occ_party',
    slug: 'party',
    name: 'Social Gathering / House Party',
    category: 'social',
    defaultFormality: 2,
    allowableFormalityRange: [1, 3],
    guidelines: [
      'Expressive styling with conversation-starter silhouettes or textures',
      'High mobility and effortless self-assured presence',
    ],
    restrictedGarmentCategories: ['black-tie-tuxedo', 'work-suit', 'morning-dress'],
    keyStyleAffinities: ['streetwear', 'korean-minimal', 'vintage', 'casual'],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'occ_college',
    slug: 'university-college',
    name: 'University / College Campus',
    category: 'academic',
    defaultFormality: 2,
    allowableFormalityRange: [1, 3],
    guidelines: [
      'Comfort-driven layered casual with strong proportions',
      'Heavyweight hoodies under work jackets, relaxed denim, timeless sneakers',
    ],
    restrictedGarmentCategories: ['full-tuxedos', 'business-suits', 'black-tie'],
    keyStyleAffinities: ['streetwear', 'workwear', 'korean-minimal', 'dark-academia', 'casual'],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'occ_wedding',
    slug: 'wedding-guest',
    name: 'Wedding Guest',
    category: 'ceremony',
    defaultFormality: 4,
    allowableFormalityRange: [3, 5],
    guidelines: [
      'Honor ceremonial formality without overshadowing the hosts',
      'Never wear all-white; choose rich navy, charcoal, or refined earthy linen suits',
      'Pair with polished oxfords or dress loafers',
    ],
    restrictedGarmentCategories: ['casual-denim', 'sneakers', 't-shirts', 'shorts', 'hoodies'],
    keyStyleAffinities: ['formal', 'old-money', 'smart-casual'],
    subParameters: ['day', 'evening'],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'occ_cultural_traditional',
    slug: 'cultural-traditional',
    name: 'Cultural / Traditional Ceremony',
    category: 'cultural',
    defaultFormality: 4,
    allowableFormalityRange: [3, 5],
    isCulturalOrTraditional: true,
    guidelines: [
      'Honors heritage textiles, bespoke regional drapery, and ceremonial reverence',
      'Welcomes sherwani, kurta, bandhgala, barong tagalog, hanbok, kimono, bespoke linen tunics, and cultural formalwear',
      'System does NOT default automatically to Western business suiting when cultural context is selected',
    ],
    restrictedGarmentCategories: ['distressed-denim', 'gym-shorts', 'graphic-hoodies'],
    keyStyleAffinities: ['old-money', 'formal', 'minimal', 'smart-casual'],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'occ_travel',
    slug: 'travel',
    name: 'Airport / Travel Transit',
    category: 'casual',
    defaultFormality: 2,
    allowableFormalityRange: [1, 3],
    guidelines: [
      'Wrinkle-resistant fabrics, functional layers for temperature shifts',
      'Easy slip-on footwear and ergonomic relaxed trousers',
    ],
    restrictedGarmentCategories: ['stiff-suits', 'impractical-footwear', 'heavy-chains'],
    keyStyleAffinities: ['techwear', 'minimal', 'korean-minimal', 'casual'],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'occ_custom',
    slug: 'custom',
    name: 'Custom Curated Event',
    category: 'social',
    defaultFormality: 3,
    allowableFormalityRange: [1, 5],
    guidelines: [
      'Adaptable contextual configuration based on custom user specification',
    ],
    keyStyleAffinities: ['minimal', 'smart-casual', 'streetwear', 'korean-minimal'],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
];
