import { StyleFamily } from '../domain/style';

export const STYLE_FAMILIES: StyleFamily[] = [
  {
    id: 'style_minimal',
    slug: 'minimal',
    name: 'Minimal',
    editorialSubtitle: 'Purity of line, stripped-back utility, monochrome quietude.',
    description:
      'Focuses on unadorned silhouettes, immaculate tailoring, and a restrained monochromatic or tonal palette.',
    styleVector: {
      formality: 3,
      structure: 4,
      volume: 3,
      colorIntensity: 1,
      contrast: 4,
      pattern: 1,
      texture: 2,
      ornamentation: 1,
      classicTrend: 2,
      utilityPolish: 4,
      genderCoding: 'androgynous',
    },
    attributes: {
      primarySilhouettes: ['clean-linear', 'relaxed-tailored'],
      dominantFits: ['tailored', 'regular', 'relaxed'],
      colorPalette: {
        primaryTones: ['black', 'white', 'charcoal', 'slate', 'raw-cream'],
        temperaturePreference: 'neutral',
        accentTolerances: 'monochromatic',
      },
      formalityRange: [2, 4],
      layeringTendency: 'minimal',
      patternIntensity: 'none',
      coreMaterials: ['heavyweight cotton', 'dry wool', 'fine silk-cotton blend', 'smooth calfskin'],
      footwearTendencies: ['clean leather low-tops', 'minimal derbies', 'chelsea boots'],
      accessoryPhilosophy: 'strictly-utilitarian',
      visualCharacter: ['architectural', 'austere', 'precise', 'uncluttered'],
    },
    characteristicGarments: ['minimal-leather-sneaker', 'tailored-slacks', 'mockneck-knit', 'clean-overcoat'],
    antiSignals: [
      'graphic prints or prominent logos',
      'heavily distressed fabrics or raw frayed hems',
      'loud primary chromatic clashes',
      'excessive ornamental hardware, chains, or studs',
      'slouchy unstructured loungewear'
    ],
    relatedStyleSlugs: ['korean-minimal', 'smart-casual'],
    keyInspirations: ['Jil Sander', 'Lemaire', 'The Row'],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'style_korean_minimal',
    slug: 'korean-minimal',
    name: 'Korean Minimal',
    editorialSubtitle: 'Fluid drapery, soft neutral harmonies, dropped shoulder softness.',
    description:
      'Blends Scandinavian restraint with Seoul streetwear proportions—oversized fluid drape, soft ecru/sage tones, and intentional volume play.',
    styleVector: {
      formality: 3,
      structure: 2,
      volume: 4,
      colorIntensity: 2,
      contrast: 2,
      pattern: 1,
      texture: 3,
      ornamentation: 2,
      classicTrend: 4,
      utilityPolish: 3,
      genderCoding: 'androgynous',
    },
    attributes: {
      primarySilhouettes: ['dropped-shoulder-fluid', 'wide-leg-break'],
      dominantFits: ['oversized', 'boxy', 'relaxed'],
      colorPalette: {
        primaryTones: ['ecru', 'dusty-sage', 'melange-grey', 'off-white', 'soft-navy'],
        temperaturePreference: 'neutral',
        accentTolerances: 'subtle-accents',
      },
      formalityRange: [2, 3],
      layeringTendency: 'moderate',
      patternIntensity: 'none',
      coreMaterials: ['brushed cotton', 'fluid gabardine', 'boiled wool', 'crepe'],
      footwearTendencies: ['chunky derbies', 'mules', 'retro runners'],
      accessoryPhilosophy: 'minimalist',
      visualCharacter: ['fluid', 'draped', 'relaxed-tailoring', 'tactile'],
    },
    characteristicGarments: ['wide-pleated-trousers', 'boxy-tee', 'deconstructed-blazer', 'chunky-derbies'],
    antiSignals: [
      'rigid stiff suiting canvas',
      'skinny spray-on denim or tapered joggers',
      'harsh contrast neons',
      'corporate executive ties or formal evening studs',
      'sharp military pocket webbing'
    ],
    relatedStyleSlugs: ['minimal', 'smart-casual'],
    keyInspirations: ['Ader Error', 'Nothing Written', 'Solid Homme'],
    timelessOrTrend: 'TREND',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'style_smart_casual',
    slug: 'smart-casual',
    name: 'Smart Casual',
    editorialSubtitle: 'Tailored versatility, refined textures, effortless transition.',
    description:
      'Effortlessly bridges executive sharpness and casual ease through structured knitwear, relaxed trousers, and deconstructed blazers.',
    styleVector: {
      formality: 3,
      structure: 3,
      volume: 3,
      colorIntensity: 3,
      contrast: 3,
      pattern: 2,
      texture: 3,
      ornamentation: 2,
      classicTrend: 2,
      utilityPolish: 4,
      genderCoding: 'unspecified',
    },
    attributes: {
      primarySilhouettes: ['structured-tapered', 'clean-tailored'],
      dominantFits: ['tailored', 'regular', 'slim'],
      colorPalette: {
        primaryTones: ['navy', 'olive', 'charcoal', 'camel', 'white'],
        temperaturePreference: 'neutral',
        accentTolerances: 'subtle-accents',
      },
      formalityRange: [2, 4],
      layeringTendency: 'moderate',
      patternIntensity: 'subtle',
      coreMaterials: ['merino wool', 'oxford cloth', 'chino twill', 'suede'],
      footwearTendencies: ['loafers', 'suede chelseas', 'leather dress sneakers'],
      accessoryPhilosophy: 'minimalist',
      visualCharacter: ['approachable', 'sharp', 'balanced', 'versatile'],
    },
    characteristicGarments: ['knit-polo', 'oxford-shirt', 'tailored-chinos', 'penny-loafers'],
    antiSignals: [
      'athletic gymwear, track pants, or graphic hoodies',
      'extreme deconstructed distressing or raw hems',
      'black-tie evening tuxedos or opera pumps',
      'tactical molle webbing or heavy cargo pouches',
      'high-sheen plastic outerwear'
    ],
    relatedStyleSlugs: ['minimal', 'old-money'],
    keyInspirations: ['Brunello Cucinelli', 'Club Monaco', "Drake's"],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'style_old_money',
    slug: 'old-money',
    name: 'Old Money',
    editorialSubtitle: 'Subdued heritage, collegiate poise, timeless noble fabrication.',
    description:
      'Rooted in bespoke generational elegance—cable-knit cashmere, pleats, signet rings, rich navy blazers, and loafers with quiet pedigree.',
    styleVector: {
      formality: 4,
      structure: 4,
      volume: 2,
      colorIntensity: 2,
      contrast: 3,
      pattern: 2,
      texture: 4,
      ornamentation: 3,
      classicTrend: 1,
      utilityPolish: 5,
      genderCoding: 'unspecified',
    },
    attributes: {
      primarySilhouettes: ['traditional-tailored', 'pleated-straight'],
      dominantFits: ['tailored', 'regular'],
      colorPalette: {
        primaryTones: ['cream', 'hunter-green', 'rich-navy', 'burgundy', 'camel'],
        temperaturePreference: 'warm',
        accentTolerances: 'subtle-accents',
      },
      formalityRange: [3, 5],
      layeringTendency: 'moderate',
      patternIntensity: 'subtle',
      coreMaterials: ['cashmere', 'tweed', 'piqué cotton', 'corduroy', 'silk'],
      footwearTendencies: ['penny loafers', 'horsebit loafers', 'oxfords'],
      accessoryPhilosophy: 'minimalist',
      visualCharacter: ['patrimonial', 'understated', 'classic', 'patina'],
    },
    characteristicGarments: ['cable-knit-cashmere', 'wool-blazer', 'pleated-wool-trousers', 'horsebit-loafers'],
    antiSignals: [
      'synthetic technical shells (nylon gore-tex)',
      'loud streetwear graphics and logo tees',
      'chunky rubber platform soles or foam slip-ons',
      'distressed acid-wash denim',
      'cybernetic hardware or utilitarian webbing'
    ],
    relatedStyleSlugs: ['smart-casual', 'formal'],
    keyInspirations: ['Ralph Lauren Purple Label', 'Loro Piana', 'Savile Row'],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'style_streetwear',
    slug: 'streetwear',
    name: 'Streetwear',
    editorialSubtitle: 'Cultural resonance, graphic proportions, sneaker-led visual syntax.',
    description:
      'High-impact volumetric silhouettes inspired by skate, hip-hop, and youth subcultures. Characterized by heavyweight jerseys and statement footwear.',
    styleVector: {
      formality: 1,
      structure: 2,
      volume: 5,
      colorIntensity: 4,
      contrast: 4,
      pattern: 4,
      texture: 3,
      ornamentation: 4,
      classicTrend: 4,
      utilityPolish: 2,
      genderCoding: 'androgynous',
    },
    attributes: {
      primarySilhouettes: ['boxy-oversized', 'stacked-cargo'],
      dominantFits: ['oversized', 'boxy', 'relaxed'],
      colorPalette: {
        primaryTones: ['washed-black', 'vintage-white', 'earth-brown', 'cobalt', 'olive'],
        temperaturePreference: 'high-contrast',
        accentTolerances: 'bold-accents',
      },
      formalityRange: [1, 2],
      layeringTendency: 'complex',
      patternIntensity: 'expressive',
      coreMaterials: ['500gsm fleece', 'ripstop nylon', 'heavy denim', 'canvas'],
      footwearTendencies: ['retro basketball sneakers', 'skate low-tops', 'technical runners'],
      accessoryPhilosophy: 'statement',
      visualCharacter: ['bold', 'volumetric', 'graphic', 'rebellious'],
    },
    characteristicGarments: ['heavy-hoodie', 'carpenter-pants', 'skate-sneakers', 'crossbody-bag'],
    antiSignals: [
      'stiff corporate suiting ties or dinner jackets',
      'high-heeled patent stilettos or formal opera pumps',
      'conservative equestrian tweed jackets',
      'dainty fragile lace blouses'
    ],
    relatedStyleSlugs: ['techwear', 'workwear'],
    keyInspirations: ['Stüssy', 'Fear of God', 'Supreme'],
    timelessOrTrend: 'TREND',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'style_workwear',
    slug: 'workwear',
    name: 'Workwear',
    editorialSubtitle: 'Rugged resilience, utilitarian stitching, enduring indigo and canvas.',
    description:
      'Heavy-gauge heritage clothing built for endurance—chore coats, selvedge denim, double-knee duck canvas, and oiled leather work boots.',
    styleVector: {
      formality: 2,
      structure: 3,
      volume: 4,
      colorIntensity: 2,
      contrast: 2,
      pattern: 2,
      texture: 5,
      ornamentation: 1,
      classicTrend: 1,
      utilityPolish: 1,
      genderCoding: 'unspecified',
    },
    attributes: {
      primarySilhouettes: ['straight-rugged', 'box-cut-work'],
      dominantFits: ['relaxed', 'regular'],
      colorPalette: {
        primaryTones: ['indigo', 'raw-canvas-tan', 'olive-drab', 'tobacco-brown', 'faded-navy'],
        temperaturePreference: 'warm',
        accentTolerances: 'subtle-accents',
      },
      formalityRange: [1, 3],
      layeringTendency: 'moderate',
      patternIntensity: 'subtle',
      coreMaterials: ['selvedge denim', 'duck canvas', 'heavy twill', 'flannel', 'waxed cotton'],
      footwearTendencies: ['service boots', 'moc-toe boots', 'canvas trainers'],
      accessoryPhilosophy: 'strictly-utilitarian',
      visualCharacter: ['rugged', 'tactile', 'grounded', 'durable'],
    },
    characteristicGarments: ['duck-canvas-chore-coat', 'selvedge-denim', 'flannel-shirt', 'service-boots'],
    antiSignals: [
      'fragile liquid silk or sheer chiffon',
      'patent black-tie evening shoes',
      'sleek bonded neoprene technical membranes',
      'tailored satin dinner lapels'
    ],
    relatedStyleSlugs: ['vintage', 'streetwear'],
    keyInspirations: ['Carhartt WIP', 'Engineered Garments', 'Post Overalls'],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'style_techwear',
    slug: 'techwear',
    name: 'Techwear',
    editorialSubtitle: 'Ergonomic utility, performance membranes, dystopian cybernetic precision.',
    description:
      'Aestheticized technical utility featuring weatherproof membranes, modular webbing, articulated joints, and monochromatic stealth.',
    styleVector: {
      formality: 2,
      structure: 4,
      volume: 3,
      colorIntensity: 1,
      contrast: 2,
      pattern: 1,
      texture: 3,
      ornamentation: 4,
      classicTrend: 5,
      utilityPolish: 2,
      genderCoding: 'androgynous',
    },
    attributes: {
      primarySilhouettes: ['articulated-taper', 'modular-outer'],
      dominantFits: ['tailored', 'relaxed'],
      colorPalette: {
        primaryTones: ['jet-black', 'graphite', 'gunmetal', 'concrete-grey'],
        temperaturePreference: 'cool',
        accentTolerances: 'monochromatic',
      },
      formalityRange: [1, 2],
      layeringTendency: 'complex',
      patternIntensity: 'none',
      coreMaterials: ['Gore-Tex', 'Cordura', 'Schoeller dryskin', 'bonded ripstop'],
      footwearTendencies: ['Gore-Tex trail runners', 'tactical combat boots'],
      accessoryPhilosophy: 'strictly-utilitarian',
      visualCharacter: ['sleek', 'armored', 'functional', 'futuristic'],
    },
    characteristicGarments: ['technical-shell', 'articulated-cargos', 'trail-runners', 'messenger-bag'],
    antiSignals: [
      'vintage hand-knit cable sweaters or tweed blazers',
      'romantic floral prints or pastel ruffles',
      'delicate thin-soled loafers or suede espadrilles',
      'classic heritage wax canvas jackets'
    ],
    relatedStyleSlugs: ['streetwear', 'minimal'],
    keyInspirations: ['Acronym', "Arc'teryx Veilance", 'Stone Island Shadow Project'],
    timelessOrTrend: 'TREND',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'style_dark_academia',
    slug: 'dark-academia',
    name: 'Dark Academia',
    editorialSubtitle: 'Melancholic scholasticism, autumnal wools, romantic historical layering.',
    description:
      'Romantic vintage scholasticism celebrating classic literature, heavy woolen tweeds, trench coats, argyle knits, and burnished leather brogues.',
    styleVector: {
      formality: 3,
      structure: 3,
      volume: 3,
      colorIntensity: 2,
      contrast: 2,
      pattern: 3,
      texture: 5,
      ornamentation: 3,
      classicTrend: 2,
      utilityPolish: 4,
      genderCoding: 'unspecified',
    },
    attributes: {
      primarySilhouettes: ['layered-tailored', 'high-waisted-pleat'],
      dominantFits: ['tailored', 'regular', 'relaxed'],
      colorPalette: {
        primaryTones: ['dark-brown', 'charcoal', 'forest-green', 'oxblood', 'warm-beige'],
        temperaturePreference: 'warm',
        accentTolerances: 'subtle-accents',
      },
      formalityRange: [2, 4],
      layeringTendency: 'complex',
      patternIntensity: 'subtle',
      coreMaterials: ['tweed', 'herringbone wool', 'corduroy', 'leather', 'brushed flannel'],
      footwearTendencies: ['oxfords', 'derby brogues', 'monk straps'],
      accessoryPhilosophy: 'layered',
      visualCharacter: ['scholarly', 'nostalgic', 'moody', 'intellectual'],
    },
    characteristicGarments: ['tweed-blazer', 'corduroy-trousers', 'lambswool-scarf', 'oxford-shoes'],
    antiSignals: [
      'bright synthetic neon activewear',
      'futuristic techwear webbing or metallic accents',
      'beachwear, espadrilles, or flip-flops',
      'ultra-minimalist stark white sneakers',
      'boxy graphic skate tees'
    ],
    relatedStyleSlugs: ['old-money', 'vintage'],
    keyInspirations: ['Donna Tartt aesthetic', 'Margaret Howell', 'Boglioli'],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'style_vintage',
    slug: 'vintage',
    name: 'Vintage',
    editorialSubtitle: 'Archival nostalgia, patina garments, counter-trend silhouettes.',
    description:
      'Curated mid-to-late 20th century garments chosen for character, unique aging, nostalgic cuts, and subversive juxtaposition.',
    styleVector: {
      formality: 2,
      structure: 3,
      volume: 4,
      colorIntensity: 3,
      contrast: 3,
      pattern: 3,
      texture: 4,
      ornamentation: 3,
      classicTrend: 2,
      utilityPolish: 2,
      genderCoding: 'unspecified',
    },
    attributes: {
      primarySilhouettes: ['high-waist-wide-leg', 'cropped-boxy-leather'],
      dominantFits: ['relaxed', 'regular', 'boxy'],
      colorPalette: {
        primaryTones: ['faded-indigo', 'patina-brown', 'washed-mustard', 'cream', 'terracotta'],
        temperaturePreference: 'warm',
        accentTolerances: 'bold-accents',
      },
      formalityRange: [1, 3],
      layeringTendency: 'moderate',
      patternIntensity: 'expressive',
      coreMaterials: ['aged leather', 'faded denim', 'rayon', 'bouclé wool', 'vintage jersey'],
      footwearTendencies: ['aged combat boots', 'retro runners', 'western boots'],
      accessoryPhilosophy: 'statement',
      visualCharacter: ['eccentric', 'archival', 'tactile', 'personal'],
    },
    characteristicGarments: ['aged-leather-jacket', 'faded-denim', 'retro-trainers', 'camp-collar-shirt'],
    antiSignals: [
      'pristine seamless synthetic performance shells',
      'corporate executive pinstripes',
      'ultra-sleek minimalist seamless bonded footwear',
      'pure modern techwear membranes'
    ],
    eraTendencies: ['50s', '60s', '70s', '80s', '90s'],
    relatedStyleSlugs: ['workwear', 'dark-academia'],
    keyInspirations: ['Bode', 'Kapital', 'Our Legacy'],
    timelessOrTrend: 'TIMELESS',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'style_experimental',
    slug: 'experimental',
    name: 'Experimental',
    editorialSubtitle: 'Deconstructive geometry, boundary-pushing drapery, avant-garde disruption.',
    description:
      'Subverts conventional fashion rules through asymmetric cuts, distorted proportions, raw edges, and unconventional texture combinations.',
    styleVector: {
      formality: 3,
      structure: 3,
      volume: 5,
      colorIntensity: 2,
      contrast: 5,
      pattern: 3,
      texture: 5,
      ornamentation: 4,
      classicTrend: 5,
      utilityPolish: 2,
      genderCoding: 'androgynous',
    },
    attributes: {
      primarySilhouettes: ['asymmetric-drape', 'volumetric-cocoon'],
      dominantFits: ['oversized', 'boxy'],
      colorPalette: {
        primaryTones: ['pitch-black', 'bone', 'concrete', 'rust', 'slate-grey'],
        temperaturePreference: 'cool',
        accentTolerances: 'bold-accents',
      },
      formalityRange: [2, 4],
      layeringTendency: 'complex',
      patternIntensity: 'expressive',
      coreMaterials: ['crinkled nylon', 'boiled wool', 'waxed canvas', 'raw-edged jersey'],
      footwearTendencies: ['platform boots', 'architectural derby sneakers', 'tabi boots'],
      accessoryPhilosophy: 'statement',
      visualCharacter: ['avant-garde', 'provocative', 'sculptural', 'bold'],
    },
    characteristicGarments: ['asymmetric-drape-coat', 'dropped-crotch-trousers', 'sculptural-boots', 'raw-hem-tunic'],
    antiSignals: [
      'conventional business-casual chinos and polos',
      'predictable preppy cable-knits',
      'plain athletic gym shorts',
      'mass-market suburban department store basics'
    ],
    relatedStyleSlugs: ['techwear', 'minimal'],
    keyInspirations: ['Rick Owens', 'Yohji Yamamoto', 'Maison Margiela'],
    timelessOrTrend: 'TREND',
    reviewDate: '2026-10-01',
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
];
