import { StyleFamily } from '../domain/style';

export const STYLE_FAMILIES: StyleFamily[] = [
  {
    id: 'style_minimal',
    slug: 'minimal',
    name: 'Minimal',
    editorialSubtitle: 'Purity of line, stripped-back utility, monochrome quietude.',
    description:
      'Focuses on unadorned silhouettes, immaculate tailoring, and a restrained monochromatic or tonal palette.',
    attributes: {
      primarySilhouettes: ['clean-linear', 'relaxed-tailored'],
      dominantFits: ['tailored', 'regular', 'relaxed'],
      colorPalette: {
        primaryTones: ['black', 'white', 'charcoal', 'slate', 'raw-cream'],
        temperaturePreference: 'neutral',
        accentTolerances: 'monochromatic',
      },
      formalityRange: [2, 4],
      layeringTendency: 'minimal',
      patternIntensity: 'none',
      coreMaterials: ['heavyweight cotton', 'dry wool', 'fine silk-cotton blend', 'smooth calfskin'],
      footwearTendencies: ['clean leather low-tops', 'minimal derbies', 'chelsea boots'],
      accessoryPhilosophy: 'strictly-utilitarian',
      visualCharacter: ['architectural', 'austere', 'precise', 'uncluttered'],
    },
    relatedStyleSlugs: ['korean-minimal', 'smart-casual'],
    keyInspirations: ['Jil Sander', 'Lemaire', 'The Row'],
  },
  {
    id: 'style_korean_minimal',
    slug: 'korean-minimal',
    name: 'Korean Minimal',
    editorialSubtitle: 'Fluid drapery, soft neutral harmonies, dropped shoulder softness.',
    description:
      'Blends Scandinavian restraint with Seoul streetwear proportions—oversized fluid drape, soft ecru/sage tones, and intentional volume play.',
    attributes: {
      primarySilhouettes: ['dropped-shoulder-fluid', 'wide-leg-break'],
      dominantFits: ['oversized', 'boxy', 'relaxed'],
      colorPalette: {
        primaryTones: ['ecru', 'dusty-sage', 'melange-grey', 'off-white', 'soft-navy'],
        temperaturePreference: 'neutral',
        accentTolerances: 'subtle-accents',
      },
      formalityRange: [2, 3],
      layeringTendency: 'moderate',
      patternIntensity: 'none',
      coreMaterials: ['brushed cotton', 'fluid gabardine', 'boiled wool', 'crepe'],
      footwearTendencies: ['chunky derbies', 'mules', 'retro runners'],
      accessoryPhilosophy: 'minimalist',
      visualCharacter: ['fluid', 'draped', 'relaxed-tailoring', 'tactile'],
    },
    relatedStyleSlugs: ['minimal', 'smart-casual'],
    keyInspirations: ['Ader Error', 'Nothing Written', 'Solid Homme'],
  },
  {
    id: 'style_smart_casual',
    slug: 'smart-casual',
    name: 'Smart Casual',
    editorialSubtitle: 'Tailored versatility, refined textures, effortless transition.',
    description:
      'Effortlessly bridges executive sharpness and casual ease through structured knitwear, relaxed trousers, and deconstructed blazers.',
    attributes: {
      primarySilhouettes: ['structured-tapered', 'clean-tailored'],
      dominantFits: ['tailored', 'regular', 'slim'],
      colorPalette: {
        primaryTones: ['navy', 'olive', 'charcoal', 'camel', 'white'],
        temperaturePreference: 'neutral',
        accentTolerances: 'subtle-accents',
      },
      formalityRange: [2, 4],
      layeringTendency: 'moderate',
      patternIntensity: 'subtle',
      coreMaterials: ['merino wool', 'oxford cloth', 'chino twill', 'suede'],
      footwearTendencies: ['loafers', 'suede chelseas', 'leather dress sneakers'],
      accessoryPhilosophy: 'minimalist',
      visualCharacter: ['approachable', 'sharp', 'balanced', 'versatile'],
    },
    relatedStyleSlugs: ['minimal', 'old-money'],
    keyInspirations: ['Brunello Cucinelli', 'Club Monaco', 'Drake\'s'],
  },
  {
    id: 'style_old_money',
    slug: 'old-money',
    name: 'Old Money',
    editorialSubtitle: 'Subdued heritage, collegiate poise, timeless noble fabrication.',
    description:
      'Rooted in bespoke generational elegance—cable-knit cashmere, pleats, signet rings, rich navy blazers, and loafers with quiet pedigree.',
    attributes: {
      primarySilhouettes: ['traditional-tailored', 'pleated-straight'],
      dominantFits: ['tailored', 'regular'],
      colorPalette: {
        primaryTones: ['cream', 'hunter-green', 'rich-navy', 'burgundy', 'camel'],
        temperaturePreference: 'warm',
        accentTolerances: 'subtle-accents',
      },
      formalityRange: [3, 5],
      layeringTendency: 'moderate',
      patternIntensity: 'subtle',
      coreMaterials: ['cashmere', 'tweed', 'piqué cotton', 'corduroy', 'silk'],
      footwearTendencies: ['penny loafers', 'horsebit loafers', 'oxfords'],
      accessoryPhilosophy: 'minimalist',
      visualCharacter: ['patrimonial', 'understated', 'classic', 'patina'],
    },
    relatedStyleSlugs: ['smart-casual', 'formal'],
    keyInspirations: ['Ralph Lauren Purple Label', 'Loro Piana', 'Savile Row'],
  },
  {
    id: 'style_streetwear',
    slug: 'streetwear',
    name: 'Streetwear',
    editorialSubtitle: 'Cultural resonance, graphic proportions, sneaker-led visual syntax.',
    description:
      'High-impact volumetric silhouettes inspired by skate, hip-hop, and youth subcultures. Characterized by heavyweight jerseys and statement footwear.',
    attributes: {
      primarySilhouettes: ['boxy-oversized', 'stacked-cargo'],
      dominantFits: ['oversized', 'boxy', 'relaxed'],
      colorPalette: {
        primaryTones: ['washed-black', 'vintage-white', 'earth-brown', 'cobalt', 'olive'],
        temperaturePreference: 'high-contrast',
        accentTolerances: 'bold-accents',
      },
      formalityRange: [1, 2],
      layeringTendency: 'complex',
      patternIntensity: 'expressive',
      coreMaterials: ['500gsm fleece', 'ripstop nylon', 'heavy denim', 'canvas'],
      footwearTendencies: ['retro basketball sneakers', 'skate low-tops', 'technical runners'],
      accessoryPhilosophy: 'statement',
      visualCharacter: ['bold', 'volumetric', 'graphic', 'rebellious'],
    },
    relatedStyleSlugs: ['techwear', 'workwear'],
    keyInspirations: ['Stüssy', 'Fear of God', 'Supreme'],
  },
  {
    id: 'style_techwear',
    slug: 'techwear',
    name: 'Techwear',
    editorialSubtitle: 'Ergonomic utility, performance membranes, dystopian cybernetic precision.',
    description:
      'Aestheticized technical utility featuring weatherproof membranes, modular webbing, articulated joints, and monochromatic stealth.',
    attributes: {
      primarySilhouettes: ['articulated-taper', 'modular-outer'],
      dominantFits: ['tailored', 'relaxed'],
      colorPalette: {
        primaryTones: ['jet-black', 'graphite', 'gunmetal', 'concrete-grey'],
        temperaturePreference: 'cool',
        accentTolerances: 'monochromatic',
      },
      formalityRange: [1, 2],
      layeringTendency: 'complex',
      patternIntensity: 'none',
      coreMaterials: ['Gore-Tex', 'Cordura', 'Schoeller dryskin', 'bonded ripstop'],
      footwearTendencies: ['Gore-Tex trail runners', 'tactical combat boots'],
      accessoryPhilosophy: 'strictly-utilitarian',
      visualCharacter: ['sleek', 'armored', 'functional', 'futuristic'],
    },
    relatedStyleSlugs: ['streetwear', 'minimal'],
    keyInspirations: ['Acronym', 'Arc\'teryx Veilance', 'Stone Island Shadow Project'],
  },
  {
    id: 'style_workwear',
    slug: 'workwear',
    name: 'Workwear',
    editorialSubtitle: 'Rugged resilience, utilitarian stitching, enduring indigo and canvas.',
    description:
      'Heavy-gauge heritage clothing built for endurance—chore coats, selvedge denim, double-knee duck canvas, and oiled leather work boots.',
    attributes: {
      primarySilhouettes: ['straight-rugged', 'box-cut-work'],
      dominantFits: ['relaxed', 'regular'],
      colorPalette: {
        primaryTones: ['indigo', 'raw-canvas-tan', 'olive-drab', 'tobacco-brown', 'faded-navy'],
        temperaturePreference: 'warm',
        accentTolerances: 'subtle-accents',
      },
      formalityRange: [1, 3],
      layeringTendency: 'moderate',
      patternIntensity: 'subtle',
      coreMaterials: ['selvedge denim', 'duck canvas', 'heavy twill', 'flannel', 'waxed cotton'],
      footwearTendencies: ['service boots', 'moc-toe boots', 'canvas trainers'],
      accessoryPhilosophy: 'strictly-utilitarian',
      visualCharacter: ['rugged', 'tactile', 'grounded', 'durable'],
    },
    relatedStyleSlugs: ['vintage', 'streetwear'],
    keyInspirations: ['Carhartt WIP', 'Engineered Garments', 'Post Overalls'],
  },
  {
    id: 'style_dark_academia',
    slug: 'dark-academia',
    name: 'Dark Academia',
    editorialSubtitle: 'Melancholic scholasticism, autumnal wools, romantic historical layering.',
    description:
      'Romantic vintage scholasticism celebrating classic literature, heavy woolen tweeds, trench coats, argyle knits, and burnished leather brogues.',
    attributes: {
      primarySilhouettes: ['layered-tailored', 'high-waisted-pleat'],
      dominantFits: ['tailored', 'regular', 'relaxed'],
      colorPalette: {
        primaryTones: ['dark-brown', 'charcoal', 'forest-green', 'oxblood', 'warm-beige'],
        temperaturePreference: 'warm',
        accentTolerances: 'subtle-accents',
      },
      formalityRange: [2, 4],
      layeringTendency: 'complex',
      patternIntensity: 'subtle',
      coreMaterials: ['tweed', 'herringbone wool', 'corduroy', 'leather', 'brushed flannel'],
      footwearTendencies: ['oxfords', 'derby brogues', 'monk straps'],
      accessoryPhilosophy: 'layered',
      visualCharacter: ['scholarly', 'nostalgic', 'moody', 'intellectual'],
    },
    relatedStyleSlugs: ['old-money', 'vintage'],
    keyInspirations: ['Donna Tartt aesthetic', 'Margaret Howell', 'Boglioli'],
  },
  {
    id: 'style_vintage',
    slug: 'vintage',
    name: 'Vintage',
    editorialSubtitle: 'Archival nostalgia, patina garments, counter-trend silhouettes.',
    description:
      'Curated mid-to-late 20th century garments chosen for character, unique aging, nostalgic cuts, and subversive juxtaposition.',
    attributes: {
      primarySilhouettes: ['high-waist-wide-leg', 'cropped-boxy-leather'],
      dominantFits: ['relaxed', 'regular', 'boxy'],
      colorPalette: {
        primaryTones: ['faded-indigo', 'patina-brown', 'washed-mustard', 'cream', 'terracotta'],
        temperaturePreference: 'warm',
        accentTolerances: 'bold-accents',
      },
      formalityRange: [1, 3],
      layeringTendency: 'moderate',
      patternIntensity: 'expressive',
      coreMaterials: ['aged leather', 'faded denim', 'rayon', 'bouclé wool', 'vintage jersey'],
      footwearTendencies: ['aged combat boots', 'retro runners', 'western boots'],
      accessoryPhilosophy: 'statement',
      visualCharacter: ['eccentric', 'archival', 'tactile', 'personal'],
    },
    relatedStyleSlugs: ['workwear', 'dark-academia'],
    keyInspirations: ['Bode', 'Kapital', 'Our Legacy'],
  },
  {
    id: 'style_formal',
    slug: 'formal',
    name: 'Formal',
    editorialSubtitle: 'Uncompromising sartorial precision, ceremonial gravity, pure proportions.',
    description:
      'Unwavering sartorial etiquette—canvassed suiting, crisp poplin shirts, peak lapels, silk ties, and mirror-shined calfskin shoes.',
    attributes: {
      primarySilhouettes: ['impeccably-tailored', 'clean-linear-break'],
      dominantFits: ['tailored', 'slim'],
      colorPalette: {
        primaryTones: ['midnight-navy', 'pure-black', 'charcoal', 'crisp-white'],
        temperaturePreference: 'neutral',
        accentTolerances: 'subtle-accents',
      },
      formalityRange: [4, 5],
      layeringTendency: 'moderate',
      patternIntensity: 'subtle',
      coreMaterials: ['Super 130s wool', 'silk satin', 'sea-island cotton', 'velvet'],
      footwearTendencies: ['oxfords', 'wholecuts', 'patent evening slippers'],
      accessoryPhilosophy: 'strictly-utilitarian',
      visualCharacter: ['authoritative', 'dignified', 'impeccable', 'statuesque'],
    },
    relatedStyleSlugs: ['old-money', 'smart-casual'],
    keyInspirations: ['Tom Ford', 'Gieves & Hawkes', 'Brioni'],
  },
  {
    id: 'style_casual',
    slug: 'casual',
    name: 'Casual',
    editorialSubtitle: 'Everyday ease, soft fabrics, effortless unpretentious comfort.',
    description:
      'Approachable, effortless daily wear calibrated for high comfort without descending into careless disarray.',
    attributes: {
      primarySilhouettes: ['natural-relaxed', 'comfortable-taper'],
      dominantFits: ['regular', 'relaxed'],
      colorPalette: {
        primaryTones: ['heather-grey', 'white', 'washed-blue', 'khaki', 'navy'],
        temperaturePreference: 'neutral',
        accentTolerances: 'subtle-accents',
      },
      formalityRange: [1, 2],
      layeringTendency: 'minimal',
      patternIntensity: 'subtle',
      coreMaterials: ['organic jersey', 'cotton fleece', 'stretch denim', 'linen'],
      footwearTendencies: ['clean canvas sneakers', 'casual slip-ons'],
      accessoryPhilosophy: 'strictly-utilitarian',
      visualCharacter: ['comfortable', 'laidback', 'unforced', 'accessible'],
    },
    relatedStyleSlugs: ['smart-casual', 'workwear'],
    keyInspirations: ['Uniqlo U', 'A.P.C.', 'Everlane'],
  },
  {
    id: 'style_experimental',
    slug: 'experimental',
    name: 'Experimental',
    editorialSubtitle: 'Deconstructive geometry, boundary-pushing drapery, avant-garde disruption.',
    description:
      'Subverts conventional fashion rules through asymmetric cuts, distorted proportions, raw edges, and unconventional texture combinations.',
    attributes: {
      primarySilhouettes: ['asymmetric-drape', 'volumetric-cocoon'],
      dominantFits: ['oversized', 'boxy'],
      colorPalette: {
        primaryTones: ['pitch-black', 'bone', 'concrete', 'rust', 'slate-grey'],
        temperaturePreference: 'cool',
        accentTolerances: 'bold-accents',
      },
      formalityRange: [2, 4],
      layeringTendency: 'complex',
      patternIntensity: 'expressive',
      coreMaterials: ['crinkled nylon', 'boiled wool', 'waxed canvas', 'raw-edged jersey'],
      footwearTendencies: ['platform boots', 'architectural derby sneakers', 'tabi boots'],
      accessoryPhilosophy: 'statement',
      visualCharacter: ['avant-garde', 'provocative', 'sculptural', 'bold'],
    },
    relatedStyleSlugs: ['techwear', 'minimal'],
    keyInspirations: ['Rick Owens', 'Yohji Yamamoto', 'Maison Margiela'],
  },
];
